export const teamsObjectList = [
  { homeTeam: 'Central Football W', awayTeam: 'Eastern Suburbs W' },
  { homeTeam: 'Canterbury United W', awayTeam: 'Auckland United W' },
  { homeTeam: 'Morelia Ud. Michoacana', awayTeam: 'Delfines de Abasolo' },
  { homeTeam: 'Western Springs W', awayTeam: 'Waterside Karori W' },
  { homeTeam: 'Nacional', awayTeam: 'Jong Aruba' },
  { homeTeam: 'Búhos UNISON', awayTeam: 'Xolos de Hermosillo' },
  { homeTeam: 'Western Springs', awayTeam: 'Wellington Olympic' },
  { homeTeam: 'Geoje Citizen', awayTeam: 'Sejong Vanesse' },
  { homeTeam: 'Seoul United', awayTeam: 'Dangjin Citizen' },
  { homeTeam: 'Japan W', awayTeam: 'South Korea W' },
  { homeTeam: 'Metaloglobus', awayTeam: 'CSM Reşiţa' },
  { homeTeam: 'Bačka Topola U19', awayTeam: 'Spartak Subotica U19' },
  { homeTeam: 'Taiwan W', awayTeam: 'Haiti W' },
  { homeTeam: 'Panserraikos U19', awayTeam: 'AEK Athens U19' },
  { homeTeam: 'Třinec', awayTeam: 'Hanácká' },
  { homeTeam: 'Vratimov', awayTeam: 'Petřvald na Moravě' },
  { homeTeam: 'Aritma Praha', awayTeam: 'Jiskra Domažlice II' },
  { homeTeam: 'NMŠK 1922 Bratislava', awayTeam: 'Rohožník' },
  { homeTeam: 'Malut United', awayTeam: 'Barito Putera' },
  { homeTeam: 'Lucchese U19', awayTeam: 'Audace Cerignola U19' },
  { homeTeam: 'Champasak United', awayTeam: 'Namtha United' },
  { homeTeam: 'Pustá Polom', awayTeam: 'Opava II' },
  { homeTeam: 'Panathinaikos U19', awayTeam: 'Aris U19' },
  { homeTeam: 'Žilina U19', awayTeam: 'Ružomberok U19' },
  { homeTeam: 'BSF Women', awayTeam: 'Allerød W' },
  { homeTeam: 'Iskra', awayTeam: 'FC Stăuceni' },
  { homeTeam: 'Rudňany', awayTeam: 'Rožňava' },
  { homeTeam: 'SC Sopron W', awayTeam: 'Tatabánya W' },
  { homeTeam: 'Wisła Kraków U19', awayTeam: 'Arka Gdynia U19' },
  { homeTeam: 'Piast Gliwice II', awayTeam: 'ROW Rybnik' },
  { homeTeam: 'Mustang Ostaszewo', awayTeam: 'RKS Lech Rypin' },
  { homeTeam: 'Jaguar Gdańsk', awayTeam: 'Czarni Pruszcz Gdański' },
  { homeTeam: 'Grom Nowy Staw', awayTeam: 'Radunia Stężyca' },
  { homeTeam: 'Cremonese U20', awayTeam: 'Lecce U20' },
  { homeTeam: 'Lazio U20', awayTeam: 'Sampdoria U20' },
  { homeTeam: 'Stal Mielec II', awayTeam: 'Stal Łańcut' },
  { homeTeam: 'Kalwarianka Kalwaria', awayTeam: 'Pcimianka' },
  { homeTeam: 'Orzeł Ryczów', awayTeam: 'Nieciecza II' },
  { homeTeam: 'Hansa Rostock U19', awayTeam: 'BAK 07 U19' },
  { homeTeam: 'Mainz 05 U19', awayTeam: 'Darmstadt 98 U19' },
  { homeTeam: 'Eintracht Frankfurt U19', awayTeam: 'FSV Frankfurt U19' },
  { homeTeam: 'Rot-Weiß Erfurt U19', awayTeam: 'Werder Bremen U19' },
  { homeTeam: 'Unterhaching U19', awayTeam: 'Augsburg U19' },
  { homeTeam: 'Slovan Liberec U19', awayTeam: 'Viktoria Plzeň U19' },
  { homeTeam: 'Salernitana U19', awayTeam: 'Benevento U19' },
  { homeTeam: 'Spezia U19', awayTeam: 'Cosenza U19' },
  { homeTeam: 'Livyi Bereh U19', awayTeam: 'Zorya Luhansk U19' },
  { homeTeam: 'Kotwica Kołobrzeg II', awayTeam: 'Iskierka Śmierdnica' },
  { homeTeam: 'Biali Sądów', awayTeam: 'Sparta Gryfice' },
  { homeTeam: 'Gavia Choszczno', awayTeam: 'MKP Szczecinek' },
  { homeTeam: 'Pendikspor  U19', awayTeam: 'Manisa FK U19' },
  { homeTeam: 'Alanyaspor U19', awayTeam: 'Altay U19' },
  { homeTeam: 'Antalyaspor U19', awayTeam: 'Altınordu U19' },
  { homeTeam: 'Boluspor U19', awayTeam: 'Ankaragücü U19' },
  { homeTeam: 'Gibraltar W', awayTeam: 'Andorra W' },
  { homeTeam: 'Gerlachov', awayTeam: 'Kechnec' },
  { homeTeam: 'Myanmar W', awayTeam: 'Hong Kong W' },
  { homeTeam: 'Glostrup', awayTeam: 'AB Tårnby' },
  { homeTeam: 'B 1908', awayTeam: 'Karlslunde' },
  { homeTeam: 'Bristol Rovers U18', awayTeam: 'Forest Green Rovers U18' },
  { homeTeam: 'Oxford United U18', awayTeam: 'Cheltenham Town U18' },
  { homeTeam: 'Plymouth Argyle U18', awayTeam: 'Exeter City U18' },
  { homeTeam: 'AFC Wimbledon U18', awayTeam: 'Cambridge United U18' },
  { homeTeam: 'Stevenage U18', awayTeam: 'Northampton Town U18' },
  { homeTeam: 'Excelsior U21', awayTeam: 'Den Bosch U21' },
  { homeTeam: 'Eugendorf', awayTeam: 'Neumarkt' },
  { homeTeam: 'Jagiellonia U19', awayTeam: 'Górnik Zabrze U19' },
  { homeTeam: 'Lechia Gdańsk U19', awayTeam: 'Legia Warszawa U19' },
  { homeTeam: 'Colchester United U18', awayTeam: 'Cardiff City U18' },
  { homeTeam: 'Ipswich Town U18', awayTeam: 'Bristol City U18' },
  { homeTeam: 'Millwall U18', awayTeam: 'Brentford U18' },
  { homeTeam: 'Queens Park Rangers U18', awayTeam: 'AFC Bournemouth U18' },
  { homeTeam: 'Swansea City U18', awayTeam: 'Watford U18' },
  { homeTeam: 'Chemik Bydgoszcz', awayTeam: 'Start Pruszcz' },
  { homeTeam: 'Orlęta Aleksandrów Kuj.', awayTeam: 'Sparta Brodnica' },
  { homeTeam: 'Lipno Stęszew', awayTeam: 'Polonia Chodzież' },
  { homeTeam: 'Oskar Przysucha', awayTeam: 'Talent Warszawa' },
  { homeTeam: 'Greuther Fürth U19', awayTeam: 'Ingolstadt U19' },
  { homeTeam: 'Sesvete U19', awayTeam: 'Graničar Đurđevac U19' },
  { homeTeam: 'Pescara U19', awayTeam: 'Avellino U19' },
  { homeTeam: 'Blackburn Rovers U18', awayTeam: 'Everton U18' },
  { homeTeam: 'Wolves U18', awayTeam: 'Stoke City U18' },
  { homeTeam: 'Middlesbrough U18', awayTeam: 'Manchester City U18' },
  { homeTeam: 'Crystal Palace U18', awayTeam: 'Leicester City U18' },
  { homeTeam: 'Southampton U18', awayTeam: 'Chelsea U18' },
  { homeTeam: 'Gubbio U19', awayTeam: 'Potenza Calcio U19' },
  { homeTeam: 'Trabzonspor U19', awayTeam: 'Samsunspor U19' },
  { homeTeam: 'Medyk Konin II', awayTeam: 'UKS Loczki' },
  { homeTeam: 'Sparta Rotterdam U19', awayTeam: 'Feyenoord U19' },
  { homeTeam: 'Samut Sakhon City', awayTeam: 'Rajpracha' },
  { homeTeam: 'Accrington Stanley U18', awayTeam: 'Doncaster Rovers U18' },
  { homeTeam: 'Preston North End U18', awayTeam: 'Notts County U18' },
  { homeTeam: 'Rotherham U18', awayTeam: 'Mansfield Town U18' },
  { homeTeam: 'Shrewsbury Town U18', awayTeam: 'Huddersfield Town U18' },
  { homeTeam: 'Wrexham U18', awayTeam: 'Port Vale U18' },
  { homeTeam: 'Escola Varsovia U19', awayTeam: 'Lech Poznań U19' },
  { homeTeam: 'Jablonec U19', awayTeam: 'Vysočina Jihlava U19' },
  { homeTeam: 'Luton Town U18', awayTeam: 'Bromley U18' },
  { homeTeam: 'Sheffield Wednesday U18', awayTeam: 'Wigan Athletic U18' },
  { homeTeam: 'Ümraniyespor', awayTeam: 'Yeni Malatyaspor' },
  { homeTeam: 'Stuttgart U19', awayTeam: 'Saarbrucken U19' },
  { homeTeam: 'West Bromwich Albion U21', awayTeam: 'Manchester City U21' },
  { homeTeam: 'Utrecht U19', awayTeam: 'Twente / Heracles U19' },
  { homeTeam: 'AZ U19', awayTeam: 'Ajax U19' },
  { homeTeam: 'Walsall U18', awayTeam: 'Harrogate Town U18' },
  { homeTeam: 'Klarenbeek W', awayTeam: 'Saestum II W' },
  { homeTeam: 'Åssiden IF', awayTeam: 'Bærum' },
  { homeTeam: 'Viking II', awayTeam: 'Brann II' },
  { homeTeam: 'Follo', awayTeam: 'Grorud' },
  { homeTeam: 'Junkeren', awayTeam: 'Alta' },
  { homeTeam: 'Kjelsås', awayTeam: 'Strømmen' },
  { homeTeam: 'Strindheim', awayTeam: 'Gjøvik-Lyn' },
  { homeTeam: 'Tromsdalen', awayTeam: 'Stjørdals-Blink' },
  { homeTeam: 'Vålerenga II', awayTeam: 'Eidsvold' },
  { homeTeam: 'IFK Norrköping U19', awayTeam: 'Kalmar U19' },
  { homeTeam: 'Hammarby U19', awayTeam: 'Stocksund U19' },
  { homeTeam: 'Halmstad U19', awayTeam: 'Öster U19' },
  { homeTeam: 'Häcken U19', awayTeam: 'Djurgården U19' },
  { homeTeam: 'AIK U19', awayTeam: 'Helsingborg U19' },
  { homeTeam: 'IFK Göteborg U19', awayTeam: 'GIF Sundsvall U19' },
  { homeTeam: 'NPM Silmet', awayTeam: 'FC Elva II' },
  { homeTeam: 'Maardu Linnameeskond', awayTeam: 'Rakvere Tarvas' },
  { homeTeam: 'FCI Tallinn', awayTeam: 'FC Tallinn II' },
  { homeTeam: 'Tartu Kalev II', awayTeam: 'Tartu Welco II' },
  { homeTeam: 'Ajax Lasnamae', awayTeam: 'Viimsi II' },
  { homeTeam: 'Võru FC Helios', awayTeam: 'Helios' },
  { homeTeam: 'Odder', awayTeam: 'Lyseng' },
  { homeTeam: 'Schalke 04', awayTeam: 'Greuther Fürth' },
  { homeTeam: 'Elversberg', awayTeam: 'Hamburger SV' },
  { homeTeam: 'AaB U19', awayTeam: 'Horsens U19' },
  { homeTeam: 'Kjellerup', awayTeam: 'Vorup' },
  { homeTeam: 'NKP Podhale', awayTeam: 'Chełmianka Chełm' },
  { homeTeam: 'Unia Tarnów', awayTeam: 'Korona Kielce II' },
  { homeTeam: 'OKS', awayTeam: 'Horsens II' },
  { homeTeam: 'B 1913', awayTeam: 'Marienlyst' },
  { homeTeam: 'Tarup-Paarup', awayTeam: 'Hedensted' },
  { homeTeam: 'Sundby W', awayTeam: 'Ølstykke' },
  { homeTeam: 'Dassendorf', awayTeam: 'Altona 93' },
  { homeTeam: 'Anker Wismar', awayTeam: 'Lichtenberg' },
  { homeTeam: 'Portsmouth U18', awayTeam: 'Newport County U18' },
  { homeTeam: 'Speranța Drochia', awayTeam: 'Victoria' },
  { homeTeam: 'Floreşti', awayTeam: 'Milsami' },
  { homeTeam: 'Thalgau', awayTeam: 'Bramberg' },
  { homeTeam: 'Siezenheim', awayTeam: 'Hallwang' },
  { homeTeam: 'Werder Bremen III', awayTeam: 'Aumund-Vegesack' },
  { homeTeam: 'Brinkumer SV', awayTeam: 'TuRa Bremen' },
  { homeTeam: 'Fleetwood Town U18', awayTeam: 'Coventry City U18' },
  { homeTeam: 'Peterborough U18', awayTeam: 'Birmingham City U18' },
  { homeTeam: 'Wisła Dobrzyń nad Wisłą', awayTeam: 'Pogoń Mogilno' },
  { homeTeam: 'Ursus Warszawa', awayTeam: 'Troszyn' },
  { homeTeam: 'Juventus U20', awayTeam: 'Roma U20' },
  { homeTeam: 'Watra Białka Tatrzańska', awayTeam: 'Sokół Słopnice' },
  { homeTeam: 'Magdeburg U19', awayTeam: 'Wolfsburg U19' },
  { homeTeam: 'Osnabrück U19', awayTeam: 'Hannover 96 U19' },
  { homeTeam: 'Slovácko U19', awayTeam: 'České Budějovice U19' },
  { homeTeam: 'Metalac GM U19', awayTeam: 'Partizan U19' },
  { homeTeam: 'OFK Beograd U19', awayTeam: 'Trayal Kruševac U19' },
  { homeTeam: 'Ina Goleniów', awayTeam: 'Olimp Gościno' },
  { homeTeam: 'KPS Chemik Police', awayTeam: 'Dąb Dębno' },
  { homeTeam: 'Manchester United U18', awayTeam: 'Nottingham Forest U18' },
  { homeTeam: 'Tottenham Hotspur U18', awayTeam: 'West Bromwich Albion U18' },
  { homeTeam: 'Norwich City U18', awayTeam: 'Arsenal U18' },
  { homeTeam: 'Panadería Pulido', awayTeam: 'CD Mensajero' },
  { homeTeam: 'MOSP Białystok', awayTeam: 'Tur Bielsk Podlaski' },
  { homeTeam: 'Ohrid', awayTeam: 'Vardarski' },
  { homeTeam: 'FK Bashkimi Kumanovo', awayTeam: 'Sasa' },
  { homeTeam: 'Grănicerul', awayTeam: 'Ocniţa' },
  { homeTeam: 'Steaua Nordului', awayTeam: 'Zimbru II' },
  { homeTeam: 'EFA Visoca', awayTeam: 'Țarigrad' },
  { homeTeam: 'Sireți', awayTeam: 'Maiak Chirsova' },
  { homeTeam: 'Codru Călărași II', awayTeam: 'Socol Copceac' },
  { homeTeam: 'Real Succes', awayTeam: 'La Familia' },
  { homeTeam: 'FC Chișinău', awayTeam: 'Constructorul Leova' },
  { homeTeam: 'Oguzsport', awayTeam: 'Congaz' },
  { homeTeam: 'LFA Szczecin W', awayTeam: 'Włókniarz Białystok' },
  { homeTeam: 'Blackpool U18', awayTeam: 'Chesterfield U18' },
  { homeTeam: 'Salford City U18', awayTeam: 'Lincoln City U18' },
  { homeTeam: 'Turan Res.', awayTeam: 'Kapaz Res.' },
  { homeTeam: 'Watford', awayTeam: 'Blackburn Rovers' },
  { homeTeam: 'Vranov nad Topľou', awayTeam: 'Lipany' },
  { homeTeam: 'Blumenthaler SV', awayTeam: 'Hemelingen' },
  { homeTeam: 'NorthEast United', awayTeam: 'Jamshedpur' },
  { homeTeam: 'Aber Valley', awayTeam: 'Swansea University' },
  { homeTeam: 'Spišská Nová Ves', awayTeam: 'Slovan Bratislava' },
  { homeTeam: 'Rēzekne / BJSS', awayTeam: 'Rīgas FS II' },
  { homeTeam: 'Middelfart', awayTeam: 'Fremad Amager' },
  { homeTeam: 'Luzern U19', awayTeam: 'Thun U19' },
  { homeTeam: 'Sion U19', awayTeam: 'Grasshoppers U19' },
  { homeTeam: 'Team Ticino U19', awayTeam: 'Young Boys U19' },
  { homeTeam: 'Tårnby FF', awayTeam: 'Herlev' },
  { homeTeam: 'Wiener SC', awayTeam: 'Donaufeld' },
  { homeTeam: 'Deutsche Jugend Kraft Vilzing', awayTeam: 'Greuther Fürth II' },
  { homeTeam: 'Union Sandersdorf', awayTeam: 'Budissa Bautzen' },
  { homeTeam: 'RSV Eintracht', awayTeam: 'Magdeburg II' },
  { homeTeam: 'Auerbach', awayTeam: 'Krieschow' },
  { homeTeam: 'Einheit Wernigerode', awayTeam: 'SC Freital' },
  { homeTeam: 'Wismut Gera', awayTeam: 'Germania Halberstadt' },
  { homeTeam: 'Blau-Weiß Zorbau', awayTeam: 'Einheit Rudolstadt' },
  { homeTeam: 'FC Grimma', awayTeam: 'VfL Halle' },
  { homeTeam: 'Nordmark Satrup', awayTeam: 'Preußen Reinfeld' },
  { homeTeam: 'Rotenhof', awayTeam: 'VfR Neumünster' },
  { homeTeam: 'Union Neumünster', awayTeam: 'Eckernförder SV' },
  { homeTeam: 'Lübeck II', awayTeam: 'TSB Flensburg' },
  { homeTeam: 'Heider SV', awayTeam: 'Eidertal Molfsee' },
  { homeTeam: 'Rödinghausen', awayTeam: 'Türkspor Dortmund' },
  { homeTeam: 'LUV Graz', awayTeam: 'Geretsberg / Bürmoos' },
  { homeTeam: 'Ravensburg', awayTeam: 'Nöttingen' },
  { homeTeam: 'Pirmasens', awayTeam: 'Wormatia Worms' },
  { homeTeam: 'Koblenz', awayTeam: 'Arminia Ludwigshafen' },
  { homeTeam: 'Schott Mainz', awayTeam: 'Eisbachtal' },
  { homeTeam: 'Innsbrucker AC', awayTeam: 'Fügen' },
  { homeTeam: 'VfB Lübeck', awayTeam: 'VfB Oldenburg' },
  { homeTeam: 'Grödig', awayTeam: 'Seekirchen' },
  { homeTeam: 'Golling', awayTeam: 'ASV Salzburg' },
  { homeTeam: 'Clachnacuddin II', awayTeam: 'Orkney' },
  { homeTeam: 'Partizán Osrblie', awayTeam: 'Javorník Makov' },
  { homeTeam: 'Spartak Medzilaborce', awayTeam: 'Sokol Ľubotice' },
  { homeTeam: 'Pavlovce nad Uhom', awayTeam: 'Spartak Medzev' },
  { homeTeam: 'Sobrance Sobranecko', awayTeam: 'Svidník' },
  { homeTeam: 'Hatvan W', awayTeam: 'KNLE' },
  { homeTeam: 'Cracovia U19', awayTeam: 'Odra Opole U19' },
  { homeTeam: 'TS Woltmershausen', awayTeam: 'Eiche Horn' },
  { homeTeam: 'TuS Geretsried', awayTeam: 'Hallbergmoos-Goldach' },
  { homeTeam: 'Dozamet Nowa Sól', awayTeam: 'Pogoń Skwierzyna' },
  { homeTeam: 'Syrena Zbąszynek', awayTeam: 'Promień Żary' },
  { homeTeam: 'Unia Solec Kujawski', awayTeam: 'Tłuchowia Tłuchowo' },
  { homeTeam: 'Tarpan Mrocza', awayTeam: 'Cuiavia Inowrocław' },
  { homeTeam: 'Polonia Bydgoszcz', awayTeam: 'Pomorzanin Serock' },
  { homeTeam: 'Centra Ostrów', awayTeam: 'Huragan Pobiedziska' },
  { homeTeam: 'Kolejarz Chojnice', awayTeam: 'KS Wierzyca Pelplin' },
  { homeTeam: 'Hetman Włoszczowa', awayTeam: 'Klimontowianka Klimontów' },
  { homeTeam: 'Meerbusch U19', awayTeam: 'Meppen U19' },
  { homeTeam: 'Hennef 05 U19', awayTeam: 'Wehen Wiesbaden U19' },
  { homeTeam: 'MEAP Nisou', awayTeam: 'Peyia' },
  { homeTeam: 'Akritas', awayTeam: 'Spartakos Kitiou' },
  { homeTeam: 'Halkanoras', awayTeam: 'Anagennisi Deryneia' },
  { homeTeam: 'Grafičar U19', awayTeam: 'Crvena Zvezda U19' },
  { homeTeam: 'Rijeka U19', awayTeam: 'HNK Gorica U19' },
  { homeTeam: 'Liverpool U18', awayTeam: 'Sunderland U18' },
  { homeTeam: 'Wissa Szczuczyn', awayTeam: 'Turośnianka' },
  { homeTeam: 'Promień Mońki', awayTeam: 'Czarni Czarna Białost.' },
  { homeTeam: 'Altglienicke II', awayTeam: 'Fortuna Biesdorf' },
  { homeTeam: 'Denzlingen', awayTeam: 'FC Teningen' },
  { homeTeam: 'Hafen Rostock', awayTeam: 'Torgelow-Ueckermünde' },
  { homeTeam: 'Warnemünde', awayTeam: 'Greifswalder II' },
  { homeTeam: 'Kühlungsborn', awayTeam: 'Pampow' },
  { homeTeam: 'Güstrow', awayTeam: 'Bentwisch' },
  { homeTeam: 'Asteras Petriti', awayTeam: 'Ermis Amyntaio' },
  { homeTeam: 'Polanka nad Odrou', awayTeam: 'Krnov' },
  { homeTeam: 'Banants', awayTeam: 'Ararat' },
  { homeTeam: 'Al Draih', awayTeam: 'Al Entesar' },
  { homeTeam: 'Panchor Murai', awayTeam: 'MS ABDB' },
  { homeTeam: 'Skaštice', awayTeam: 'Holešov' },
  { homeTeam: 'Břidličná', awayTeam: 'Havířov' },
  { homeTeam: 'Humpolec', awayTeam: 'Vrchovina' },
  { homeTeam: 'Velká Bíteš', awayTeam: 'Velké Meziříčí' },
  { homeTeam: 'St. Gallen U19', awayTeam: 'Lausanne-Sport U19' },
  { homeTeam: 'Dukla Praha W', awayTeam: 'Prague Raptors W' },
  { homeTeam: 'RKAV Volendam', awayTeam: 'Excelsior Maassluis' },
  { homeTeam: 'Noordwijk', awayTeam: "ADO '20" },
  { homeTeam: 'FCM Ungheni', awayTeam: 'Olimp Comrat' },
  { homeTeam: 'HSV Hoek', awayTeam: "FC 's-Gravenzande" },
  { homeTeam: 'SteDoCo', awayTeam: 'Smitshoek' },
  { homeTeam: 'Dyce Juniors', awayTeam: 'Culter' },
  { homeTeam: 'Fraserburgh United', awayTeam: 'Buchanhaven Hearts' },
  { homeTeam: 'Sunnybank', awayTeam: 'Bridge of Don Thistle' },
  { homeTeam: 'Maud', awayTeam: 'East End' },
  { homeTeam: 'Newmachar United', awayTeam: 'Colony Park' },
  { homeTeam: "Banks O' Dee II", awayTeam: 'Ellon United' },
  { homeTeam: 'Budućnost Banovići', awayTeam: 'Vis Kosova' },
  { homeTeam: 'Forstinning', awayTeam: 'Garmisch-Partenkirchen' },
  { homeTeam: 'Bogacica', awayTeam: 'LZS Starościn' },
  { homeTeam: 'Polonia Głubczyce', awayTeam: 'Fortuna Głogówek' },
  { homeTeam: 'Piotrówka', awayTeam: 'Victoria Chróścice' },
  { homeTeam: 'Viktoria Köln U19', awayTeam: 'Kaiserslautern U19' },
  { homeTeam: 'Arsenal Ceska Lipa', awayTeam: 'Kladno' },
  { homeTeam: 'Lierse Kempenzonen', awayTeam: 'Moldavo II' },
  { homeTeam: 'Ajax Amateurs W', awayTeam: 'Stiens W' },
  { homeTeam: 'Sparta Rotterdam II W', awayTeam: 'Knickerbockers W' },
  { homeTeam: 'Masfut', awayTeam: 'Gulf Heroes' },
  { homeTeam: 'Al Urooba', awayTeam: 'Bani Yas' },
  { homeTeam: 'B36', awayTeam: 'Skála' },
  { homeTeam: 'Caersws', awayTeam: 'Bangor 1876' },
  { homeTeam: 'Dugo Selo', awayTeam: 'Mladost Ždralovi' },
  { homeTeam: 'Hrvace', awayTeam: 'Kustošija' },
  { homeTeam: 'Jadran LP', awayTeam: 'Radnik Križevci' },
  { homeTeam: 'Uljanik', awayTeam: 'NK Marsonia 1909' },
  { homeTeam: 'Ried II', awayTeam: 'Treibach' },
  { homeTeam: 'Wisłoka Dębica', awayTeam: 'Wiązownica' },
  { homeTeam: 'Kreuzlingen', awayTeam: 'Tuggen' },
  { homeTeam: 'Rijnsburgse Boys', awayTeam: 'Barendrecht' },
  { homeTeam: 'Quick Boys', awayTeam: 'AFC' },
  { homeTeam: 'Sparta Rotterdam II', awayTeam: 'Spakenburg' },
  { homeTeam: 'TOGB W', awayTeam: 'VVSB' },
  { homeTeam: 'GOES', awayTeam: 'Rijnvogels' },
  { homeTeam: 'Kaiserslautern II', awayTeam: 'Idar-Oberstein' },
  { homeTeam: 'Mechtersheim', awayTeam: 'TuS RW Koblenz' },
  { homeTeam: 'Morlautern', awayTeam: 'SV Auersmacher' },
  { homeTeam: 'Jeddeloh', awayTeam: 'Werder Bremen II' },
  { homeTeam: 'Admira Dornbirn', awayTeam: 'Göfis' },
  { homeTeam: 'Alness United', awayTeam: 'Inverness Athletic' },
  { homeTeam: 'Bonar Bridge', awayTeam: 'Halkirk United' },
  { homeTeam: 'St Duthus', awayTeam: 'Bunillidh Thistle' },
  { homeTeam: 'Clydebank', awayTeam: 'Benburb' },
  { homeTeam: 'Darvel', awayTeam: 'Hurlford United' },
  { homeTeam: 'Weidenhausen', awayTeam: 'Bayern Alzenau' },
  { homeTeam: 'Fernwald', awayTeam: 'Hanau 93' },
  { homeTeam: 'Starše', awayTeam: 'Hajdina' },
  { homeTeam: 'Bistrc', awayTeam: 'Kranj' },
  { homeTeam: 'Šencur', awayTeam: 'Rudar Trbovlje' },
  { homeTeam: 'Dingolfing', awayTeam: 'ASV Burglengenfeld' },
  { homeTeam: 'Vasas Kubala Akadémia', awayTeam: 'Gödöllői W' },
  { homeTeam: 'Wigtown & Bladnoch', awayTeam: 'Creetown' },
  { homeTeam: 'Schammelsdorf', awayTeam: 'Röllbach' },
  { homeTeam: 'LKS Bełk', awayTeam: 'Kuźnia Ustroń' },
  { homeTeam: 'Warta Działoszyn', awayTeam: 'Orkan Buczek' },
  { homeTeam: 'Zryw Wygoda', awayTeam: 'Widzew Łódź II' },
  { homeTeam: 'Czarni Witnica', awayTeam: 'Ilanka Rzepin' },
  { homeTeam: 'Łokietek Brześć Kuj.', awayTeam: 'Noteć Łabiszyn' },
  { homeTeam: 'Pilica Białobrzegi', awayTeam: 'KTS Weszło' },
  { homeTeam: 'Starogard Gdański', awayTeam: 'Bytovia Bytów' },
  { homeTeam: 'Pomezania Malbork', awayTeam: 'Gryf Wejherowo' },
  { homeTeam: 'Pogoń Lębork', awayTeam: 'Chojniczanka Chojnice II' },
  { homeTeam: 'Bologna U20', awayTeam: 'Udinese U20' },
  { homeTeam: 'Pogoń 1945 Staszów', awayTeam: 'Moravia Morawica' },
  { homeTeam: 'Bredene W', awayTeam: 'Moldavo W' },
  { homeTeam: 'Ladies Genk II', awayTeam: 'Standard Liège II W' },
  { homeTeam: 'VVC Brasschaat W', awayTeam: 'Svelta Melsele W' },
  { homeTeam: 'Šibenik U19', awayTeam: 'Split U19' },
  { homeTeam: 'Liverpool U21', awayTeam: 'Everton U21' },
  { homeTeam: 'LSK Hansa', awayTeam: 'Rotenburger SV' },
  { homeTeam: 'Catania U19', awayTeam: 'Catanzaro U19' },
  { homeTeam: 'Foggia U19', awayTeam: 'Giugliano U19' },
  { homeTeam: 'KS Warmia Grajewo', awayTeam: 'Supraślanka Supraśl' },
  { homeTeam: 'Metropolitan Police', awayTeam: 'Guernsey' },
  { homeTeam: 'Hochwald', awayTeam: 'VFB Linz' },
  { homeTeam: 'Maccabi Petah Tikva U19', awayTeam: 'Hapoel Rishon LeZion U19' },
  { homeTeam: 'Maccabi Haifa U19', awayTeam: 'Hapoel Raanana U19' },
  { homeTeam: 'Vechta', awayTeam: 'Holthausen-Biene' },
  { homeTeam: 'Pomorac', awayTeam: 'Kraljevica' },
  { homeTeam: 'Moso Sugar', awayTeam: 'Inter Star' },
  { homeTeam: 'AZS KU Uniwersytetu', awayTeam: 'Praga Warszawa' },
  { homeTeam: 'Picerno U19', awayTeam: 'Cavese U19' },
  { homeTeam: 'Pineto U19', awayTeam: 'Sorrento U19' },
  { homeTeam: 'Fort William', awayTeam: 'Alness United' },
  { homeTeam: 'UVV W', awayTeam: 'WV-HEDW W' },
  { homeTeam: 'Barendrecht W', awayTeam: 'VDZ W' },
  { homeTeam: 'Jordan W', awayTeam: 'Philippines W' },
  { homeTeam: 'CSKA Moskva', awayTeam: 'Fakel' },
  { homeTeam: 'Ruthin Town', awayTeam: 'Guilsfield' },
  { homeTeam: 'Aarau U19', awayTeam: 'Servette U19' },
  { homeTeam: 'Stuttgart', awayTeam: 'Holstein Kiel' },
  { homeTeam: 'Augsburg', awayTeam: 'Borussia Dortmund' },
  { homeTeam: 'Hollenbach', awayTeam: 'Balingen' },
  { homeTeam: 'FV Engers 07', awayTeam: 'Eppelborn' },
  { homeTeam: 'Viktoria Herxheim', awayTeam: 'Gonsenheim' },
  { homeTeam: 'SV Unter-Flockenbach', awayTeam: 'Waldgirmes' },
  { homeTeam: 'Rot-Weiß Walldorf', awayTeam: 'Eddersheim' },
  { homeTeam: 'Saar Saarbrücken', awayTeam: 'Ballweiler-Wecklingen' },
  { homeTeam: 'Carnoustie Panmure', awayTeam: 'Forfar West End' },
  { homeTeam: 'Coupar Angus', awayTeam: 'Dundee North End' },
  { homeTeam: 'Downfield', awayTeam: 'Blairgowrie' },
  { homeTeam: 'Dundee St James', awayTeam: 'Forfar United' },
  { homeTeam: 'Letham', awayTeam: 'Broughty Athletic' },
  { homeTeam: 'Lochee Harp', awayTeam: 'Lochee United' },
  { homeTeam: 'Tayport', awayTeam: 'Scone Thistle' },
  { homeTeam: 'Linx', awayTeam: 'FC Waldkirch' },
  { homeTeam: 'Rudar U19', awayTeam: 'Bravo U19' },
  { homeTeam: 'Olympique Béja', awayTeam: 'Club Africain' },
  { homeTeam: 'Tekstilac Ravnice', awayTeam: 'Tigar Sveta Nedelja' },
  { homeTeam: 'Hajduk Split', awayTeam: 'Lokomotiva Zagreb' },
  { homeTeam: 'Manchester City', awayTeam: 'Southampton' },
  { homeTeam: 'Newport County', awayTeam: 'Fleetwood Town' },
  { homeTeam: 'Ballinamallard United', awayTeam: 'H&W Welders' },
  { homeTeam: 'Dundee', awayTeam: 'St. Johnstone' },
  { homeTeam: 'Enosis', awayTeam: 'Ethnikos Achna' },
  { homeTeam: 'Gørslev', awayTeam: 'GVI' },
  { homeTeam: 'União Nogueirense U19', awayTeam: 'Porto U19' },
  { homeTeam: 'SPG Motz Silz', awayTeam: 'Kundl' },
  { homeTeam: 'Carlisle City', awayTeam: 'Seaham Red Star' },
  { homeTeam: 'West Auckland Town', awayTeam: 'Boro Rangers' },
  { homeTeam: 'Amberg', awayTeam: 'Kareth Lappersdorf' },
  { homeTeam: 'Újpest', awayTeam: 'Csepel W' },
  { homeTeam: 'Kelen W', awayTeam: 'Paksi SE W' },
  { homeTeam: 'Berkhamsted', awayTeam: 'Ware' },
  { homeTeam: 'Whitchurch Alport', awayTeam: 'Uttoxeter Town' },
  { homeTeam: 'Tividale', awayTeam: 'Lichfield City' },
  { homeTeam: 'Hain', awayTeam: 'Alemannia Haibach' },
  { homeTeam: 'Palatia Limbach', awayTeam: 'Rastpfuhl' },
  { homeTeam: 'Mettlach Merzig', awayTeam: 'Rot-WeiY Hasborn' },
  { homeTeam: 'Abbey Hey', awayTeam: 'Glossop North End' },
  { homeTeam: 'Chadderton', awayTeam: 'Isle of Man' },
  { homeTeam: 'Charnock Richard', awayTeam: 'Longridge Town' },
  { homeTeam: 'Litherland Remyca', awayTeam: 'Ramsbottom United' },
  { homeTeam: 'Pilkington XXX', awayTeam: 'AFC Liverpool' },
  { homeTeam: 'Prestwich Heys', awayTeam: 'Padiham' },
  { homeTeam: 'West Didsbury & Chorlton', awayTeam: 'St Helens' },
  { homeTeam: 'Kimberley Miners Welfare', awayTeam: 'Harrowby United' },
  { homeTeam: 'Newark Flowserve', awayTeam: 'Lincoln United' },
  { homeTeam: 'Newark Town', awayTeam: 'Hucknall Town' },
  { homeTeam: 'Shirebrook Town', awayTeam: 'Bourne Town' },
  { homeTeam: 'Skegness Town', awayTeam: 'Gresley' },
  { homeTeam: 'Wisbech Town', awayTeam: 'Melton Town' },
  { homeTeam: 'Aylestone Park', awayTeam: 'St Neots Town' },
  { homeTeam: 'Bugbrooke St Michaels', awayTeam: 'Leicester Nirvana' },
  { homeTeam: 'Coventry United', awayTeam: 'Hinckley AFC' },
  { homeTeam: 'Easington Sports', awayTeam: 'Sileby Rangers' },
  { homeTeam: 'Oadby Town', awayTeam: 'Yaxley' },
  { homeTeam: 'Godmanchester Rovers', awayTeam: 'Lutterworth Town' },
  { homeTeam: 'Beverley Town', awayTeam: 'Rossington Main' },
  { homeTeam: 'Bottesford Town', awayTeam: 'Pickering Town' },
  { homeTeam: 'Frickley Athletic', awayTeam: 'Hallam' },
  { homeTeam: 'Goole', awayTeam: 'Knaresborough Town' },
  { homeTeam: 'Handsworth Parramore', awayTeam: 'Thackley' },
  { homeTeam: 'Penistone Church', awayTeam: 'Silsden AFC' },
  { homeTeam: 'Sawbridgeworth Town', awayTeam: 'Halstead Town FC' },
  { homeTeam: 'Newhaven', awayTeam: 'Little Common' },
  { homeTeam: 'Saltdean United', awayTeam: 'Crawley Down Gatwick' },
  { homeTeam: 'Shoreham', awayTeam: 'Petersfield Town' },
  { homeTeam: 'Loenhout W', awayTeam: 'Herent W' },
  { homeTeam: 'Witton Albion', awayTeam: 'Stafford Rangers' },
  { homeTeam: 'Maldon & Tiptree', awayTeam: 'Witham Town' },
  { homeTeam: 'Ascot United', awayTeam: 'Leatherhead' },
  { homeTeam: 'Farnham Town', awayTeam: 'Horndean' },
  { homeTeam: 'Harrow Borough', awayTeam: 'Moneyfields' },
  { homeTeam: 'Hayes & Yeading United', awayTeam: 'Hartley Wintney FC' },
  { homeTeam: 'Raynes Park Vale', awayTeam: 'Binfield' },
  { homeTeam: 'Beckenham Town', awayTeam: 'Deal Town' },
  { homeTeam: 'Erith Town', awayTeam: 'Broadbridge Heath' },
  { homeTeam: 'Margate', awayTeam: 'Eastbourne Town' },
  { homeTeam: 'Three Bridges', awayTeam: 'East Grinstead Town' },
  { homeTeam: 'Malberg', awayTeam: 'Schneifel-Stadtkyll' },
  { homeTeam: 'British Airways', awayTeam: 'Edgware Town' },
  { homeTeam: 'Burnham', awayTeam: 'Broadfields United' },
  { homeTeam: 'Harefield United', awayTeam: 'Ardley United' },
  { homeTeam: 'North Greenford United', awayTeam: 'Berks County' },
  { homeTeam: 'Virginia Water', awayTeam: 'Reading City' },
  { homeTeam: 'Wallingford & Crowmarsh', awayTeam: 'Hilltop' },
  { homeTeam: 'Horley Town', awayTeam: 'Balham' },
  { homeTeam: 'Tooting & Mitcham United', awayTeam: 'Sandhurst Town FC' },
  { homeTeam: 'Extension Gunners', awayTeam: 'VTM' },
  { homeTeam: 'Security Systems', awayTeam: 'TAFIC' },
  { homeTeam: 'Recreativo do Libolo', awayTeam: 'São Salvador' },
  { homeTeam: 'KR', awayTeam: 'HK' },
  { homeTeam: 'Sauchie Juniors', awayTeam: 'Buckie Thistle' },
  { homeTeam: 'Irvine Meadow', awayTeam: 'Civil Service Strollers' },
  { homeTeam: 'Hill Of Beath Hawthorn', awayTeam: "Bo'ness United" },
  { homeTeam: 'Linlithgow Rose', awayTeam: 'Clachnacuddin' },
  { homeTeam: 'Auchinleck Talbot', awayTeam: 'Broxburn Athletic' },
  { homeTeam: 'Worksop Town', awayTeam: 'United of Manchester' },
  { homeTeam: 'Macclesfield', awayTeam: 'Ashton United' },
  { homeTeam: 'Chasetown', awayTeam: 'Belper Town' },
  { homeTeam: 'Stourbridge', awayTeam: 'Alvechurch' },
  { homeTeam: 'Gloucester City', awayTeam: 'Coleshill Town' },
  { homeTeam: 'Dover Athletic', awayTeam: 'Sittingbourne' },
  { homeTeam: 'Hadley', awayTeam: 'Hastings United' },
  { homeTeam: 'Basford United', awayTeam: 'Anstey Nomads' },
  { homeTeam: 'Brentwood Town', awayTeam: 'Cray Valley PM' },
  { homeTeam: 'Hungerford Town', awayTeam: 'Yate Town' },
  { homeTeam: 'Tavistock', awayTeam: 'Winchester City' },
  { homeTeam: 'Bolton Wanderers', awayTeam: 'Peterborough United' },
  { homeTeam: 'Mechelen W', awayTeam: 'Bilzen United' },
  { homeTeam: 'Fortuna Sittard', awayTeam: 'Groningen' },
  { homeTeam: 'Umm Salal', awayTeam: 'Al Khor' },
  { homeTeam: 'Bürmoos', awayTeam: 'Anif' },
  { homeTeam: 'Stomil Olsztyn II', awayTeam: 'Olimpia Olsztynek' },
  { homeTeam: 'Brea', awayTeam: 'Atletico Monzon' },
  { homeTeam: 'Pasaia KE', awayTeam: 'Basconia' },
  { homeTeam: 'OB', awayTeam: 'Esbjerg' },
  { homeTeam: 'Austria Wien', awayTeam: 'Wattens' },
  { homeTeam: 'Young Boys II', awayTeam: 'Vevey Sports' },
  { homeTeam: 'Ahlerstedt / Ottendorf', awayTeam: 'Neetze' },
  { homeTeam: 'Atlético Artajonés', awayTeam: 'Cantolagua' },
  { homeTeam: 'La Cruz U19', awayTeam: 'Real Madrid U19' },
  { homeTeam: 'USM Oujda', awayTeam: 'Chabab Atlas Khénifra' },
  { homeTeam: 'Olympique Dcheïra', awayTeam: 'Rapide Oued Zem' },
  { homeTeam: 'Raja Beni Mellal', awayTeam: 'Mouloudia Oujda' },
  { homeTeam: 'Sassuolo', awayTeam: 'Modena' },
  { homeTeam: 'Diamenty Warszawa W', awayTeam: 'Słupczanka Słupca W' },
  { homeTeam: 'Trier-Tarforst', awayTeam: 'Cosmos Koblenz' },
  { homeTeam: 'FV Morbach', awayTeam: 'Mosella Schweich' },
  { homeTeam: 'Dundalk U20', awayTeam: 'Sligo Rovers U20' },
  { homeTeam: 'Ajman', awayTeam: 'Al Wasl' },
  { homeTeam: 'Al Jazira', awayTeam: 'Al Khaleej' },
  { homeTeam: 'Bellinzona', awayTeam: 'Neuchâtel Xamax' },
  { homeTeam: 'Oldenburger SV', awayTeam: 'Hohenwestedt' },
  { homeTeam: 'Emmen', awayTeam: 'Lachen / Altendorf' },
  { homeTeam: 'Dobrovce', awayTeam: 'Krško' },
  { homeTeam: 'Brežice', awayTeam: 'Fužinar' },
  { homeTeam: 'Ruch Wysokie Mazowieckie', awayTeam: 'Olimpia Zambrów' },
  { homeTeam: 'Faraones Texcoco II', awayTeam: 'Matamoros' },
  { homeTeam: "DZC '68 W", awayTeam: 'Wittenhorst W' },
  { homeTeam: 'Nooit Gedacht W', awayTeam: 'Heerenveense Boys W' },
  { homeTeam: 'RKSV Nuenen II W', awayTeam: 'DSS II W' },
  { homeTeam: "Hapoel Be'er Sheva", awayTeam: 'Maccabi Bnei Raina' },
  { homeTeam: 'Real Zaragoza', awayTeam: 'CD Castellón' },
  { homeTeam: 'Crowborough Athletic', awayTeam: 'Hassocks' },
  { homeTeam: 'Al Quwa Al Jawiya', awayTeam: 'Diala' },
  { homeTeam: 'Locarno', awayTeam: 'Brunnen' },
  { homeTeam: 'Leones Negros UdeG Premier', awayTeam: 'Real Apodaca' },
  { homeTeam: 'Club Unión', awayTeam: 'Cañoneros II' },
  { homeTeam: 'Mechelen II W', awayTeam: 'Kontich W' },
  { homeTeam: 'Dessel Sport', awayTeam: 'Thes Sport' },
  { homeTeam: 'Bahrain SC', awayTeam: 'Al Shabab' },
  { homeTeam: 'KFC Turnhout', awayTeam: 'Betekom' },
  { homeTeam: 'Nieciecza', awayTeam: 'Arka Gdynia' },
  { homeTeam: 'Sporting Hasselt', awayTeam: 'Spouwen-Mopertingen' },
  { homeTeam: 'Hoogstraten VV', awayTeam: 'Lyra-Lierse Berlaar' },
  { homeTeam: 'Al Hilal', awayTeam: 'Al Taawon' },
  { homeTeam: 'Artesanos Metepec II', awayTeam: 'Orishas Tepeji' },
  { homeTeam: 'Botafogo W', awayTeam: 'Duque de Caxias' },
  { homeTeam: 'Vasco da Gama W', awayTeam: 'Boavista W' },
  { homeTeam: 'Hamilton Parish', awayTeam: 'North Village Rams' },
  { homeTeam: 'Grêmio W', awayTeam: 'Juventude W' },
  { homeTeam: 'Brasil Farroupilha W', awayTeam: 'Vida SAF W' },
  { homeTeam: 'Univap Apodi', awayTeam: 'Alecrim' },
  { homeTeam: 'América EC de Pedrinhas', awayTeam: 'Canindé' },
  { homeTeam: "Maccabi Giv'at Shmuel", awayTeam: 'Sektzia Nes Tziona' },
  { homeTeam: 'Hapoel Bnei Kseifa', awayTeam: 'FC Ramla' },
  { homeTeam: 'Sint-Truiden', awayTeam: 'KVC Westerlo' },
  { homeTeam: 'MTK', awayTeam: 'Újpest' },
  { homeTeam: 'Atalanta', awayTeam: 'Hellas Verona' },
  { homeTeam: 'Real Madrid', awayTeam: 'FC Barcelona' },
  { homeTeam: 'Cambrefort', awayTeam: 'Gourbeyre' },
  { homeTeam: 'CD Universidad Católica', awayTeam: 'CS Emelec' },
  { homeTeam: 'Union Omaha', awayTeam: 'Central Valley Fuego' },
  { homeTeam: 'Águila Azteca', awayTeam: 'Caballeros de Córdoba' },
  { homeTeam: 'Aguacateros CDU', awayTeam: 'Correcaminos UAT II' },
  { homeTeam: 'Brazil W', awayTeam: 'Colombia W' },
  { homeTeam: 'PR Sol', awayTeam: 'PR Surf' },
  { homeTeam: 'Metropolitan', awayTeam: 'MK Elite' },
  { homeTeam: 'Petroleros de Salamanca', awayTeam: 'Irapuato' },
  { homeTeam: 'Magos', awayTeam: 'Fut-Car' },
  { homeTeam: 'Atlético Leones', awayTeam: 'Irapuato II' },
  { homeTeam: 'Santa Ana del Conde', awayTeam: 'Necaxa II' },
  { homeTeam: 'Fénix CFAR', awayTeam: 'Legado del Centenario' },
  { homeTeam: 'Atlético Acaponeta', awayTeam: 'Castores Gobrantacto' },
  { homeTeam: 'Halcones de Nayarit', awayTeam: 'Dorados de Sinaloa II' },
  { homeTeam: 'Black Bulls Maputo', awayTeam: 'Textáfrica' },
];