export const teamsObjectList = [
  {
    homeTeam: 'Chattanooga Red Wolves',
    awayTeam: 'Lexington',
    over15Average: 95,
    bttsAverage: 75,
    homePointsPerGame: 0.8,
    awayPointsPerGame: 0.5,
  },
  {
    homeTeam: 'Western Suburbs',
    awayTeam: 'Napier City Rovers',
    over15Average: 93,
    bttsAverage: 71,
    homePointsPerGame: 1.86,
    awayPointsPerGame: 2.05,
  },
  {
    homeTeam: 'West Coast Rangers W',
    awayTeam: 'Wellington Phoenix II',
    over15Average: 100,
    bttsAverage: 75,
    homePointsPerGame: 1.0,
    awayPointsPerGame: 0.0,
  },
  {
    homeTeam: 'Alajuelense',
    awayTeam: 'San Carlos',
    over15Average: 94,
    bttsAverage: 75,
    homePointsPerGame: 2.14,
    awayPointsPerGame: 2.13,
  },
  {
    homeTeam: 'Cofutpa',
    awayTeam: 'Grecia',
    over15Average: 86,
    bttsAverage: 79,
    homePointsPerGame: 1.14,
    awayPointsPerGame: 1.14,
  },
  {
    homeTeam: 'Birkenhead United',
    awayTeam: 'Wellington Phoenix Reserves',
    over15Average: 92,
    bttsAverage: 73,
    homePointsPerGame: 1.92,
    awayPointsPerGame: 1.23,
  },
  {
    homeTeam: 'LA Galaxy',
    awayTeam: 'Colorado Rapids',
    over15Average: 90,
    bttsAverage: 73,
    homePointsPerGame: 1.88,
    awayPointsPerGame: 1.47,
  },
  {
    homeTeam: 'Yokohama F. Marinos',
    awayTeam: 'Gamba Osaka',
    over15Average: 100,
    bttsAverage: 88,
    homePointsPerGame: 2.0,
    awayPointsPerGame: 3.0,
  },
  {
    homeTeam: 'Shatin',
    awayTeam: 'Central & Western',
    over15Average: 100,
    bttsAverage: 75,
    homePointsPerGame: 0.0,
    awayPointsPerGame: 3.0,
  },
  {
    homeTeam: 'Jerudong',
    awayTeam: 'AKSE Bersatu',
    over15Average: 100,
    bttsAverage: 75,
    homePointsPerGame: 0.0,
    awayPointsPerGame: 0.0,
  },
  {
    homeTeam: 'Cape Town City U23',
    awayTeam: 'Chippa United U23',
    over15Average: 94,
    bttsAverage: 75,
    homePointsPerGame: 1.86,
    awayPointsPerGame: 0.63,
  },
  {
    homeTeam: 'Kaya',
    awayTeam: 'Loyola',
    over15Average: 100,
    bttsAverage: 100,
    homePointsPerGame: 3.0,
    awayPointsPerGame: 3.0,
  },
  {
    homeTeam: 'Assumption United',
    awayTeam: 'Samut Songkhram City',
    over15Average: 83,
    bttsAverage: 83,
    homePointsPerGame: 1.17,
    awayPointsPerGame: 0.33,
  },
  {
    homeTeam: 'Chlumec nad Cidlinou',
    awayTeam: 'Mladá Boleslav U21',
    over15Average: 87,
    bttsAverage: 73,
    homePointsPerGame: 0.73,
    awayPointsPerGame: 1.18,
  },
  {
    homeTeam: 'Sparta Praha II',
    awayTeam: 'Viktoria Žižkov',
    over15Average: 83,
    bttsAverage: 75,
    homePointsPerGame: 1.83,
    awayPointsPerGame: 1.0,
  },
  {
    homeTeam: 'USC Paloma',
    awayTeam: 'Niendorfer TSV',
    over15Average: 81,
    bttsAverage: 74,
    homePointsPerGame: 1.69,
    awayPointsPerGame: 1.54,
  },
  {
    homeTeam: 'Podbeskidzie II',
    awayTeam: 'Unia Dąbrowa Górnicza',
    over15Average: 83,
    bttsAverage: 71,
    homePointsPerGame: 0.71,
    awayPointsPerGame: 1.5,
  },
  {
    homeTeam: 'Internazionale U20',
    awayTeam: 'Empoli U20',
    over15Average: 100,
    bttsAverage: 71,
    homePointsPerGame: 1.25,
    awayPointsPerGame: 0.33,
  },
  {
    homeTeam: 'Holstein Kiel U19',
    awayTeam: 'Union Berlin U19',
    over15Average: 100,
    bttsAverage: 88,
    homePointsPerGame: 1.75,
    awayPointsPerGame: 1.75,
  },
  {
    homeTeam: 'Schalke 04 U19',
    awayTeam: 'Preußen Münster U19',
    over15Average: 100,
    bttsAverage: 75,
    homePointsPerGame: 2.25,
    awayPointsPerGame: 1.5,
  },
  {
    homeTeam: 'Bayer Leverkusen U19',
    awayTeam: 'Köln U19',
    over15Average: 88,
    bttsAverage: 75,
    homePointsPerGame: 2.6,
    awayPointsPerGame: 1.75,
  },
  {
    homeTeam: 'Ulm U19',
    awayTeam: 'Bayern München U19',
    over15Average: 100,
    bttsAverage: 80,
    homePointsPerGame: 2.0,
    awayPointsPerGame: 2.4,
  },
  {
    homeTeam: 'SGS Essen',
    awayTeam: 'Wesel-Lackhausen',
    over15Average: 100,
    bttsAverage: 82,
    homePointsPerGame: 1.55,
    awayPointsPerGame: 1.55,
  },
  {
    homeTeam: 'GSS Grodzisk',
    awayTeam: 'Pułtusk W',
    over15Average: 100,
    bttsAverage: 81,
    homePointsPerGame: 0.25,
    awayPointsPerGame: 1.86,
  },
  {
    homeTeam: 'Botoșani U18',
    awayTeam: 'Sport Team U18',
    over15Average: 90,
    bttsAverage: 72,
    homePointsPerGame: 0.67,
    awayPointsPerGame: 0.6,
  },
  {
    homeTeam: 'FC Tallinn',
    awayTeam: 'Harju Jalgpallikool',
    over15Average: 94,
    bttsAverage: 76,
    homePointsPerGame: 1.29,
    awayPointsPerGame: 2.0,
  },
  {
    homeTeam: 'Staal Jørpeland',
    awayTeam: 'Madla',
    over15Average: 90,
    bttsAverage: 72,
    homePointsPerGame: 1.36,
    awayPointsPerGame: 1.52,
  },
  {
    homeTeam: 'Flint',
    awayTeam: 'Asker',
    over15Average: 86,
    bttsAverage: 72,
    homePointsPerGame: 1.16,
    awayPointsPerGame: 2.36,
  },
  {
    homeTeam: 'Gamle Oslo',
    awayTeam: 'Ullern',
    over15Average: 96,
    bttsAverage: 82,
    homePointsPerGame: 2.0,
    awayPointsPerGame: 1.32,
  },
  {
    homeTeam: 'Stabæk II',
    awayTeam: 'Strømsgodset II',
    over15Average: 92,
    bttsAverage: 74,
    homePointsPerGame: 1.24,
    awayPointsPerGame: 1.56,
  },
  {
    homeTeam: 'Skjervøy',
    awayTeam: 'Ulfstind',
    over15Average: 96,
    bttsAverage: 76,
    homePointsPerGame: 1.88,
    awayPointsPerGame: 0.84,
  },
  {
    homeTeam: 'Olivenza',
    awayTeam: 'Trujillo',
    over15Average: 93,
    bttsAverage: 72,
    homePointsPerGame: 1.0,
    awayPointsPerGame: 1.0,
  },
  {
    homeTeam: 'AD San Juan U19',
    awayTeam: 'Danok Bat U19',
    over15Average: 82,
    bttsAverage: 76,
    homePointsPerGame: 1.75,
    awayPointsPerGame: 1.5,
  },
  {
    homeTeam: 'Binh Dinh',
    awayTeam: 'Song Lam Nghe An',
    over15Average: 100,
    bttsAverage: 75,
    homePointsPerGame: 0.0,
    awayPointsPerGame: 0.0,
  },
  {
    homeTeam: 'Da Nang',
    awayTeam: 'Hai Phong',
    over15Average: 100,
    bttsAverage: 100,
    homePointsPerGame: 0.5,
    awayPointsPerGame: 0.5,
  },
  {
    homeTeam: 'Barcelona II W',
    awayTeam: 'Osasuna W',
    over15Average: 100,
    bttsAverage: 75,
    homePointsPerGame: 1.5,
    awayPointsPerGame: 2.0,
  },
  {
    homeTeam: 'Dąb Zabierzów Bocheński W',
    awayTeam: 'Iskra Tarnów W',
    over15Average: 94,
    bttsAverage: 76,
    homePointsPerGame: 1.0,
    awayPointsPerGame: 1.63,
  },
  {
    homeTeam: 'Emmen',
    awayTeam: 'Telstar',
    over15Average: 92,
    bttsAverage: 75,
    homePointsPerGame: 1.0,
    awayPointsPerGame: 1.5,
  },
  {
    homeTeam: 'Utrecht',
    awayTeam: 'Feyenoord',
    over15Average: 88,
    bttsAverage: 88,
    homePointsPerGame: 3.0,
    awayPointsPerGame: 1.8,
  },
  {
    homeTeam: 'Parma',
    awayTeam: 'Empoli',
    over15Average: 100,
    bttsAverage: 88,
    homePointsPerGame: 1.0,
    awayPointsPerGame: 1.75,
  },
  {
    homeTeam: 'Montijo',
    awayTeam: 'Moralo',
    over15Average: 79,
    bttsAverage: 71,
    homePointsPerGame: 0.86,
    awayPointsPerGame: 1.29,
  },
  {
    homeTeam: 'Nyíregyháza Spartacus',
    awayTeam: 'Zalaegerszegi TE',
    over15Average: 100,
    bttsAverage: 88,
    homePointsPerGame: 1.75,
    awayPointsPerGame: 0.25,
  },
  {
    homeTeam: 'Teplice',
    awayTeam: 'Bohemians 1905',
    over15Average: 75,
    bttsAverage: 75,
    homePointsPerGame: 0.67,
    awayPointsPerGame: 1.5,
  },
  {
    homeTeam: 'Békéscsaba',
    awayTeam: 'Honvéd W',
    over15Average: 100,
    bttsAverage: 78,
    homePointsPerGame: 1.75,
    awayPointsPerGame: 0.2,
  },
  {
    homeTeam: 'Sassuolo U20',
    awayTeam: 'Torino U20',
    over15Average: 100,
    bttsAverage: 71,
    homePointsPerGame: 1.67,
    awayPointsPerGame: 1.5,
  },
  {
    homeTeam: 'Radnički Kragujevac U19',
    awayTeam: 'Brodarac U19',
    over15Average: 74,
    bttsAverage: 74,
    homePointsPerGame: 1.6,
    awayPointsPerGame: 0.67,
  },
  {
    homeTeam: 'Berliner SC',
    awayTeam: 'Stern',
    over15Average: 90,
    bttsAverage: 80,
    homePointsPerGame: 1.1,
    awayPointsPerGame: 2.2,
  },
  {
    homeTeam: 'Hilden II',
    awayTeam: 'Amern',
    over15Average: 96,
    bttsAverage: 82,
    homePointsPerGame: 1.36,
    awayPointsPerGame: 1.09,
  },
  {
    homeTeam: 'Suhareka',
    awayTeam: 'Prishtina',
    over15Average: 88,
    bttsAverage: 75,
    homePointsPerGame: 2.25,
    awayPointsPerGame: 1.5,
  },
  {
    homeTeam: 'ATSV Sebaldsbrück',
    awayTeam: 'Schwachhausen',
    over15Average: 95,
    bttsAverage: 82,
    homePointsPerGame: 2.38,
    awayPointsPerGame: 2.22,
  },
  {
    homeTeam: 'Ha Noi',
    awayTeam: 'Hà Nội II',
    over15Average: 75,
    bttsAverage: 75,
    homePointsPerGame: 2.0,
    awayPointsPerGame: 2.0,
  },
  {
    homeTeam: 'Rimba Star',
    awayTeam: 'MS PPDB',
    over15Average: 100,
    bttsAverage: 75,
    homePointsPerGame: 3.0,
    awayPointsPerGame: 1.5,
  },
  {
    homeTeam: 'Stomil Olsztyn',
    awayTeam: 'Wisła Płock II',
    over15Average: 93,
    bttsAverage: 77,
    homePointsPerGame: 1.15,
    awayPointsPerGame: 1.5,
  },
  {
    homeTeam: 'Energie Cottbus',
    awayTeam: '1860 München',
    over15Average: 90,
    bttsAverage: 80,
    homePointsPerGame: 2.0,
    awayPointsPerGame: 2.0,
  },
  {
    homeTeam: 'FC Santa Coloma',
    awayTeam: 'La Massana',
    over15Average: 100,
    bttsAverage: 100,
    homePointsPerGame: 2.0,
    awayPointsPerGame: 0.0,
  },
  {
    homeTeam: 'Teutonia Hamburg',
    awayTeam: 'Phönix Lübeck',
    over15Average: 93,
    bttsAverage: 71,
    homePointsPerGame: 1.29,
    awayPointsPerGame: 1.62,
  },
  {
    homeTeam: 'Stal Rzeszów U19',
    awayTeam: 'Śląsk Wrocław U19',
    over15Average: 100,
    bttsAverage: 84,
    homePointsPerGame: 1.33,
    awayPointsPerGame: 2.0,
  },
  {
    homeTeam: 'Gornji Rahić',
    awayTeam: 'Radnik Hadzici',
    over15Average: 89,
    bttsAverage: 73,
    homePointsPerGame: 0.67,
    awayPointsPerGame: 1.67,
  },
  {
    homeTeam: 'IMT Novi Beograd U19',
    awayTeam: 'Čukarički U19',
    over15Average: 90,
    bttsAverage: 80,
    homePointsPerGame: 2.6,
    awayPointsPerGame: 1.4,
  },
  {
    homeTeam: 'Al Mokawloon',
    awayTeam: 'Telecom Egypt SC',
    over15Average: 100,
    bttsAverage: 100,
    homePointsPerGame: 3.0,
    awayPointsPerGame: 1.0,
  },
  {
    homeTeam: 'Al Fujairah',
    awayTeam: 'Al Jazira Al Hamra',
    over15Average: 100,
    bttsAverage: 100,
    homePointsPerGame: 1.0,
    awayPointsPerGame: 0.0,
  },
  {
    homeTeam: 'Al Bataeh',
    awayTeam: 'Al Nasr',
    over15Average: 100,
    bttsAverage: 75,
    homePointsPerGame: 0.5,
    awayPointsPerGame: 1.0,
  },
  {
    homeTeam: 'Khorfakkan U23',
    awayTeam: 'Al Jazira U23',
    over15Average: 84,
    bttsAverage: 84,
    homePointsPerGame: 0.0,
    awayPointsPerGame: 0.5,
  },
  {
    homeTeam: 'Vejle',
    awayTeam: 'Lyngby',
    over15Average: 82,
    bttsAverage: 74,
    homePointsPerGame: 0.17,
    awayPointsPerGame: 0.6,
  },
  {
    homeTeam: 'ND Slovan Ljubljana',
    awayTeam: 'Tabor Sežana',
    over15Average: 100,
    bttsAverage: 90,
    homePointsPerGame: 0.4,
    awayPointsPerGame: 1.4,
  },
  {
    homeTeam: 'Ringkøbing',
    awayTeam: 'Viby',
    over15Average: 91,
    bttsAverage: 78,
    homePointsPerGame: 1.0,
    awayPointsPerGame: 0.64,
  },
  {
    homeTeam: 'Esbjerg II',
    awayTeam: 'B 1909',
    over15Average: 91,
    bttsAverage: 73,
    homePointsPerGame: 2.18,
    awayPointsPerGame: 0.82,
  },
  {
    homeTeam: 'Buchholz',
    awayTeam: 'Victoria Hamburg',
    over15Average: 96,
    bttsAverage: 81,
    homePointsPerGame: 1.54,
    awayPointsPerGame: 1.62,
  },
  {
    homeTeam: 'Halstenbek-Rellingen',
    awayTeam: 'Türkiye',
    over15Average: 96,
    bttsAverage: 77,
    homePointsPerGame: 1.0,
    awayPointsPerGame: 1.15,
  },
  {
    homeTeam: 'Sparta Lichtenberg',
    awayTeam: 'Tasmania Berlin',
    over15Average: 89,
    bttsAverage: 73,
    homePointsPerGame: 1.44,
    awayPointsPerGame: 2.33,
  },
  {
    homeTeam: 'Heeslinger SC',
    awayTeam: 'Schöningen',
    over15Average: 84,
    bttsAverage: 72,
    homePointsPerGame: 1.77,
    awayPointsPerGame: 2.0,
  },
  {
    homeTeam: 'Krypnianka Krypno',
    awayTeam: 'Wasilków',
    over15Average: 100,
    bttsAverage: 81,
    homePointsPerGame: 1.15,
    awayPointsPerGame: 2.77,
  },
  {
    homeTeam: 'Polokwane City',
    awayTeam: 'Mamelodi Sundowns',
    over15Average: 100,
    bttsAverage: 100,
    homePointsPerGame: 2.0,
    awayPointsPerGame: 3.0,
  },
  {
    homeTeam: 'Ngozi City',
    awayTeam: 'Kayanza United',
    over15Average: 100,
    bttsAverage: 100,
    homePointsPerGame: 2.33,
    awayPointsPerGame: 1.0,
  },
  {
    homeTeam: 'Desportivo Nacala',
    awayTeam: 'Black Bulls Maputo',
    over15Average: 83,
    bttsAverage: 83,
    homePointsPerGame: 1.33,
    awayPointsPerGame: 2.13,
  },
  {
    homeTeam: 'Dinamo Minsk U19',
    awayTeam: 'Lokomotiva Zagreb U19',
    over15Average: 100,
    bttsAverage: 100,
    homePointsPerGame: 2.0,
    awayPointsPerGame: 3.0,
  },
  {
    homeTeam: 'Majantja',
    awayTeam: 'Lifofane',
    over15Average: 100,
    bttsAverage: 75,
    homePointsPerGame: 0.0,
    awayPointsPerGame: 3.0,
  },
  {
    homeTeam: 'Wisła Płock',
    awayTeam: 'Wisła Kraków',
    over15Average: 76,
    bttsAverage: 76,
    homePointsPerGame: 2.14,
    awayPointsPerGame: 0.8,
  },
  {
    homeTeam: 'Varnsdorf',
    awayTeam: 'Vlašim',
    over15Average: 100,
    bttsAverage: 84,
    homePointsPerGame: 0.67,
    awayPointsPerGame: 1.0,
  },
  {
    homeTeam: 'Berg en Dal',
    awayTeam: 'Houtvenne',
    over15Average: 94,
    bttsAverage: 76,
    homePointsPerGame: 0.63,
    awayPointsPerGame: 2.13,
  },
  {
    homeTeam: 'Šampion Celje',
    awayTeam: 'Čarda Martjanci',
    over15Average: 100,
    bttsAverage: 75,
    homePointsPerGame: 0.6,
    awayPointsPerGame: 1.6,
  },
  {
    homeTeam: 'TSV Mariendorf',
    awayTeam: 'Empor Berlin',
    over15Average: 95,
    bttsAverage: 75,
    homePointsPerGame: 2.0,
    awayPointsPerGame: 2.1,
  },
  {
    homeTeam: 'Huchting',
    awayTeam: 'FC Sparta Bremerhaven',
    over15Average: 89,
    bttsAverage: 73,
    homePointsPerGame: 1.0,
    awayPointsPerGame: 1.44,
  },
  {
    homeTeam: 'Teramo',
    awayTeam: 'Sora',
    over15Average: 76,
    bttsAverage: 76,
    homePointsPerGame: 1.88,
    awayPointsPerGame: 1.5,
  },
  {
    homeTeam: 'Seravezza',
    awayTeam: 'Poggibonsi',
    over15Average: 88,
    bttsAverage: 82,
    homePointsPerGame: 1.75,
    awayPointsPerGame: 1.75,
  },
  {
    homeTeam: 'Schüren',
    awayTeam: 'Westfalia Herne',
    over15Average: 96,
    bttsAverage: 78,
    homePointsPerGame: 1.18,
    awayPointsPerGame: 1.73,
  },
  {
    homeTeam: 'Chelsea',
    awayTeam: 'Newcastle United',
    over15Average: 88,
    bttsAverage: 75,
    homePointsPerGame: 1.25,
    awayPointsPerGame: 1.25,
  },
  {
    homeTeam: 'Eendracht Termien',
    awayTeam: 'Rupel Boom',
    over15Average: 88,
    bttsAverage: 76,
    homePointsPerGame: 1.0,
    awayPointsPerGame: 2.13,
  },
  {
    homeTeam: 'Rot Weiss Ahlen',
    awayTeam: 'Bochum II',
    over15Average: 86,
    bttsAverage: 76,
    homePointsPerGame: 1.45,
    awayPointsPerGame: 2.1,
  },
  {
    homeTeam: 'SF Baumberg',
    awayTeam: 'Mülheimer',
    over15Average: 91,
    bttsAverage: 77,
    homePointsPerGame: 0.9,
    awayPointsPerGame: 1.0,
  },
  {
    homeTeam: 'Fylde Ladies',
    awayTeam: 'Doncaster Belles W',
    over15Average: 93,
    bttsAverage: 73,
    homePointsPerGame: 0.57,
    awayPointsPerGame: 0.75,
  },
  {
    homeTeam: 'Leeds W',
    awayTeam: 'Barnsley W',
    over15Average: 100,
    bttsAverage: 77,
    homePointsPerGame: 1.86,
    awayPointsPerGame: 0.83,
  },
  {
    homeTeam: 'Vernier',
    awayTeam: 'Romontois',
    over15Average: 90,
    bttsAverage: 71,
    homePointsPerGame: 1.0,
    awayPointsPerGame: 1.55,
  },
  {
    homeTeam: 'FC Union 60 Bremen',
    awayTeam: 'Geestemünde',
    over15Average: 100,
    bttsAverage: 84,
    homePointsPerGame: 1.22,
    awayPointsPerGame: 2.11,
  },
  {
    homeTeam: 'SC Halberg Brebach 1907 eV',
    awayTeam: 'Reisbach',
    over15Average: 94,
    bttsAverage: 78,
    homePointsPerGame: 1.19,
    awayPointsPerGame: 1.63,
  },
  {
    homeTeam: 'Hellas Verona U20',
    awayTeam: 'Atalanta U20',
    over15Average: 88,
    bttsAverage: 88,
    homePointsPerGame: 1.75,
    awayPointsPerGame: 2.0,
  },
  {
    homeTeam: 'OH Leuven II W',
    awayTeam: 'Club Brugge II W',
    over15Average: 90,
    bttsAverage: 90,
    homePointsPerGame: 1.33,
    awayPointsPerGame: 1.6,
  },
  {
    homeTeam: 'The New Saints W',
    awayTeam: 'Barry Town United W',
    over15Average: 75,
    bttsAverage: 75,
    homePointsPerGame: 2.0,
    awayPointsPerGame: 2.0,
  },
  {
    homeTeam: 'Lecco U19',
    awayTeam: 'Virtus Verona U19',
    over15Average: 80,
    bttsAverage: 80,
    homePointsPerGame: 1.0,
    awayPointsPerGame: 1.6,
  },
  {
    homeTeam: 'Auggen',
    awayTeam: 'SC Lahr',
    over15Average: 90,
    bttsAverage: 75,
    homePointsPerGame: 1.3,
    awayPointsPerGame: 0.6,
  },
  {
    homeTeam: 'Rielasingen-Arlen',
    awayTeam: 'Hausen',
    over15Average: 86,
    bttsAverage: 76,
    homePointsPerGame: 1.78,
    awayPointsPerGame: 0.55,
  },
  {
    homeTeam: 'Papenburg',
    awayTeam: 'Melle 03',
    over15Average: 83,
    bttsAverage: 75,
    homePointsPerGame: 1.92,
    awayPointsPerGame: 1.75,
  },
  {
    homeTeam: 'Dodesheide',
    awayTeam: 'Bevern',
    over15Average: 84,
    bttsAverage: 75,
    homePointsPerGame: 1.08,
    awayPointsPerGame: 2.0,
  },
  {
    homeTeam: 'Grün Weiß Mühlen',
    awayTeam: 'Bad Bentheim',
    over15Average: 92,
    bttsAverage: 79,
    homePointsPerGame: 1.83,
    awayPointsPerGame: 0.25,
  },
  {
    homeTeam: 'Deutz',
    awayTeam: 'Bornheim',
    over15Average: 95,
    bttsAverage: 78,
    homePointsPerGame: 1.44,
    awayPointsPerGame: 2.5,
  },
  {
    homeTeam: 'SV Breinig',
    awayTeam: 'Eintracht Verlautenheide',
    over15Average: 100,
    bttsAverage: 94,
    homePointsPerGame: 1.63,
    awayPointsPerGame: 2.0,
  },
  {
    homeTeam: 'Hiltrup',
    awayTeam: 'Rödinghausen II',
    over15Average: 91,
    bttsAverage: 73,
    homePointsPerGame: 1.73,
    awayPointsPerGame: 1.73,
  },
  {
    homeTeam: 'RW Maaslingen',
    awayTeam: 'Mesum',
    over15Average: 87,
    bttsAverage: 73,
    homePointsPerGame: 1.55,
    awayPointsPerGame: 1.45,
  },
  {
    homeTeam: 'Peckeloh',
    awayTeam: 'Westfalia Soest',
    over15Average: 87,
    bttsAverage: 73,
    homePointsPerGame: 1.91,
    awayPointsPerGame: 1.45,
  },
  {
    homeTeam: 'Olsa Brakel',
    awayTeam: 'Sparta Petegem',
    over15Average: 88,
    bttsAverage: 76,
    homePointsPerGame: 1.38,
    awayPointsPerGame: 1.25,
  },
  {
    homeTeam: 'Horsthausen',
    awayTeam: 'Holzwickeder SC',
    over15Average: 96,
    bttsAverage: 78,
    homePointsPerGame: 1.73,
    awayPointsPerGame: 1.73,
  },
  {
    homeTeam: 'Meinerzhagen',
    awayTeam: 'Lüner SV',
    over15Average: 96,
    bttsAverage: 82,
    homePointsPerGame: 1.64,
    awayPointsPerGame: 0.82,
  },
  {
    homeTeam: 'Iserlohn',
    awayTeam: 'Sprockhövel',
    over15Average: 91,
    bttsAverage: 73,
    homePointsPerGame: 1.91,
    awayPointsPerGame: 2.09,
  },
  {
    homeTeam: 'Aubel',
    awayTeam: 'Tilffois',
    over15Average: 89,
    bttsAverage: 73,
    homePointsPerGame: 1.78,
    awayPointsPerGame: 1.67,
  },
  {
    homeTeam: 'Paksi SE',
    awayTeam: 'Kecskeméti TE',
    over15Average: 75,
    bttsAverage: 75,
    homePointsPerGame: 3.0,
    awayPointsPerGame: 0.0,
  },
  {
    homeTeam: 'Südwest Köln W',
    awayTeam: "Borussia M'gladbach II W",
    over15Average: 89,
    bttsAverage: 84,
    homePointsPerGame: 0.33,
    awayPointsPerGame: 1.67,
  },
  {
    homeTeam: 'Oberpleis',
    awayTeam: 'Wiehl',
    over15Average: 95,
    bttsAverage: 73,
    homePointsPerGame: 1.0,
    awayPointsPerGame: 1.22,
  },
  {
    homeTeam: 'Bochum',
    awayTeam: 'Bayern München',
    over15Average: 100,
    bttsAverage: 71,
    homePointsPerGame: 0.33,
    awayPointsPerGame: 2.5,
  },
  {
    homeTeam: 'Al Wakrah',
    awayTeam: 'Al Sadd',
    over15Average: 100,
    bttsAverage: 84,
    homePointsPerGame: 1.33,
    awayPointsPerGame: 1.0,
  },
  {
    homeTeam: 'Finnentrop / Bamenohl',
    awayTeam: 'SpVgg Erkenschwick',
    over15Average: 90,
    bttsAverage: 75,
    homePointsPerGame: 1.2,
    awayPointsPerGame: 1.3,
  },
  {
    homeTeam: 'Habenhauser FV',
    awayTeam: 'SC Vahr-Blockdiek',
    over15Average: 95,
    bttsAverage: 73,
    homePointsPerGame: 0.78,
    awayPointsPerGame: 0.33,
  },
  {
    homeTeam: 'VfL Vichttal',
    awayTeam: 'Teutonia Weiden',
    over15Average: 100,
    bttsAverage: 73,
    homePointsPerGame: 0.33,
    awayPointsPerGame: 2.11,
  },
  {
    homeTeam: 'Zemplín Michalovce',
    awayTeam: 'Skalica',
    over15Average: 90,
    bttsAverage: 80,
    homePointsPerGame: 1.0,
    awayPointsPerGame: 0.8,
  },
  {
    homeTeam: 'Hagen / Uthlede',
    awayTeam: 'MTV Römstedt',
    over15Average: 96,
    bttsAverage: 78,
    homePointsPerGame: 1.36,
    awayPointsPerGame: 0.45,
  },
  {
    homeTeam: 'Recreativo de Huelva',
    awayTeam: 'AD Alcorcón',
    over15Average: 73,
    bttsAverage: 73,
    homePointsPerGame: 0.56,
    awayPointsPerGame: 1.0,
  },
  {
    homeTeam: 'TuS Kirchberg',
    awayTeam: 'Ahrweiler BC',
    over15Average: 92,
    bttsAverage: 75,
    homePointsPerGame: 1.0,
    awayPointsPerGame: 1.67,
  },
  {
    homeTeam: 'SC Borgfeld',
    awayTeam: 'TuSpo Surheide',
    over15Average: 100,
    bttsAverage: 71,
    homePointsPerGame: 1.44,
    awayPointsPerGame: 1.63,
  },
  {
    homeTeam: 'Moers',
    awayTeam: 'Steele',
    over15Average: 96,
    bttsAverage: 96,
    homePointsPerGame: 1.27,
    awayPointsPerGame: 0.27,
  },
  {
    homeTeam: 'TuRU 1880 Düsseldorf',
    awayTeam: 'Unterrath',
    over15Average: 91,
    bttsAverage: 78,
    homePointsPerGame: 1.18,
    awayPointsPerGame: 1.82,
  },
  {
    homeTeam: 'Krefeld-Fischeln',
    awayTeam: 'Kapellen-Erft',
    over15Average: 87,
    bttsAverage: 73,
    homePointsPerGame: 1.18,
    awayPointsPerGame: 0.91,
  },
  {
    homeTeam: 'Bockum-Hövel',
    awayTeam: 'Westfalia Kinderhaus',
    over15Average: 82,
    bttsAverage: 73,
    homePointsPerGame: 0.64,
    awayPointsPerGame: 1.0,
  },
  {
    homeTeam: 'Nõmme United II',
    awayTeam: 'Vändra JK Vaprus',
    over15Average: 86,
    bttsAverage: 74,
    homePointsPerGame: 2.28,
    awayPointsPerGame: 1.56,
  },
  {
    homeTeam: 'Laagri II',
    awayTeam: 'Tallinna FC Zapoos',
    over15Average: 96,
    bttsAverage: 72,
    homePointsPerGame: 1.6,
    awayPointsPerGame: 1.36,
  },
  {
    homeTeam: 'Paide III',
    awayTeam: 'Hiiumaa',
    over15Average: 88,
    bttsAverage: 76,
    homePointsPerGame: 1.24,
    awayPointsPerGame: 1.2,
  },
  {
    homeTeam: 'Saue',
    awayTeam: 'Saku Sporting',
    over15Average: 94,
    bttsAverage: 76,
    homePointsPerGame: 0.92,
    awayPointsPerGame: 1.52,
  },
  {
    homeTeam: 'Flora III',
    awayTeam: 'Keila',
    over15Average: 90,
    bttsAverage: 76,
    homePointsPerGame: 1.16,
    awayPointsPerGame: 1.8,
  },
  {
    homeTeam: 'Necaxa U23',
    awayTeam: 'Toluca U23',
    over15Average: 93,
    bttsAverage: 73,
    homePointsPerGame: 1.23,
    awayPointsPerGame: 1.62,
  },
  {
    homeTeam: 'Joane',
    awayTeam: 'Os Limianos',
    over15Average: 83,
    bttsAverage: 75,
    homePointsPerGame: 1.83,
    awayPointsPerGame: 1.17,
  },
  {
    homeTeam: 'Herrensohr',
    awayTeam: 'Hertha Wiesbach',
    over15Average: 94,
    bttsAverage: 72,
    homePointsPerGame: 1.25,
    awayPointsPerGame: 1.88,
  },
  {
    homeTeam: 'Sporting Mertzig',
    awayTeam: 'Koerich',
    over15Average: 89,
    bttsAverage: 78,
    homePointsPerGame: 1.56,
    awayPointsPerGame: 1.56,
  },
  {
    homeTeam: 'Norden',
    awayTeam: 'Steinfort',
    over15Average: 95,
    bttsAverage: 73,
    homePointsPerGame: 1.67,
    awayPointsPerGame: 0.56,
  },
  {
    homeTeam: 'Young Boys',
    awayTeam: 'Blô-Weiss Medernach',
    over15Average: 95,
    bttsAverage: 84,
    homePointsPerGame: 1.67,
    awayPointsPerGame: 1.56,
  },
  {
    homeTeam: 'Jeunesse Schieren',
    awayTeam: 'Erpeldange',
    over15Average: 95,
    bttsAverage: 73,
    homePointsPerGame: 1.78,
    awayPointsPerGame: 1.11,
  },
  {
    homeTeam: 'Alliance Aischdall',
    awayTeam: 'Hosingen',
    over15Average: 89,
    bttsAverage: 78,
    homePointsPerGame: 0.89,
    awayPointsPerGame: 0.78,
  },
  {
    homeTeam: 'Sanem',
    awayTeam: 'Jeunesse Junglinster',
    over15Average: 95,
    bttsAverage: 78,
    homePointsPerGame: 2.22,
    awayPointsPerGame: 0.89,
  },
  {
    homeTeam: 'Syra Mensdorf',
    awayTeam: 'Yellow Boys Weiler',
    over15Average: 94,
    bttsAverage: 82,
    homePointsPerGame: 2.0,
    awayPointsPerGame: 1.67,
  },
  {
    homeTeam: 'Stade Marocain',
    awayTeam: 'KAC Kénitra',
    over15Average: 100,
    bttsAverage: 100,
    homePointsPerGame: 3.0,
    awayPointsPerGame: 0.0,
  },
  {
    homeTeam: 'Wydad Fès',
    awayTeam: 'JSM Laâyoune',
    over15Average: 100,
    bttsAverage: 100,
    homePointsPerGame: 3.0,
    awayPointsPerGame: 1.0,
  },
  {
    homeTeam: 'Lugano',
    awayTeam: 'Young Boys',
    over15Average: 90,
    bttsAverage: 80,
    homePointsPerGame: 2.0,
    awayPointsPerGame: 0.8,
  },
  {
    homeTeam: 'Shabab Al Ahli Dubai',
    awayTeam: 'Al Sharjah',
    over15Average: 100,
    bttsAverage: 75,
    homePointsPerGame: 3.0,
    awayPointsPerGame: 3.0,
  },
  {
    homeTeam: 'Vitesse',
    awayTeam: 'Réal du Faso',
    over15Average: 75,
    bttsAverage: 75,
    homePointsPerGame: 3.0,
    awayPointsPerGame: 0.5,
  },
  {
    homeTeam: 'Montpellier',
    awayTeam: 'Toulouse',
    over15Average: 100,
    bttsAverage: 71,
    homePointsPerGame: 1.0,
    awayPointsPerGame: 0.33,
  },
  {
    homeTeam: 'Coruxo',
    awayTeam: 'Real Valladolid II',
    over15Average: 94,
    bttsAverage: 75,
    homePointsPerGame: 1.25,
    awayPointsPerGame: 1.5,
  },
  {
    homeTeam: 'Welayta Dicha',
    awayTeam: 'Shire Endaselassie',
    over15Average: 84,
    bttsAverage: 84,
    homePointsPerGame: 3.0,
    awayPointsPerGame: 1.67,
  },
  {
    homeTeam: 'Union Berlin',
    awayTeam: 'Eintracht Frankfurt',
    over15Average: 84,
    bttsAverage: 71,
    homePointsPerGame: 3.0,
    awayPointsPerGame: 1.5,
  },
  {
    homeTeam: 'Al Arabi',
    awayTeam: 'Qatar SC',
    over15Average: 75,
    bttsAverage: 75,
    homePointsPerGame: 1.67,
    awayPointsPerGame: 2.0,
  },
  {
    homeTeam: 'Győri ETO',
    awayTeam: 'Ferencváros',
    over15Average: 100,
    bttsAverage: 71,
    homePointsPerGame: 1.5,
    awayPointsPerGame: 2.0,
  },
  {
    homeTeam: 'Al Wihdat',
    awayTeam: 'Aqaba',
    over15Average: 100,
    bttsAverage: 100,
    homePointsPerGame: 2.5,
    awayPointsPerGame: 0.0,
  },
  {
    homeTeam: 'SD Huesca',
    awayTeam: 'Almería',
    over15Average: 74,
    bttsAverage: 74,
    homePointsPerGame: 2.0,
    awayPointsPerGame: 1.17,
  },
  {
    homeTeam: 'Napredak',
    awayTeam: 'Bačka Topola',
    over15Average: 79,
    bttsAverage: 71,
    homePointsPerGame: 1.17,
    awayPointsPerGame: 1.5,
  },
  {
    homeTeam: 'Unión Comercio',
    awayTeam: 'Sporting Cristal',
    over15Average: 91,
    bttsAverage: 75,
    homePointsPerGame: 0.88,
    awayPointsPerGame: 1.56,
  },
  {
    homeTeam: 'Fuerte San Francisco U20',
    awayTeam: 'Cacahuatique U20',
    over15Average: 86,
    bttsAverage: 72,
    homePointsPerGame: 0.5,
    awayPointsPerGame: 0.57,
  },
  {
    homeTeam: 'Wisła Płock W',
    awayTeam: 'Górzno',
    over15Average: 100,
    bttsAverage: 71,
    homePointsPerGame: 1.0,
    awayPointsPerGame: 1.67,
  },
  {
    homeTeam: 'Pro Training Camp',
    awayTeam: 'Salamanca Cuquío',
    over15Average: 88,
    bttsAverage: 75,
    homePointsPerGame: 2.25,
    awayPointsPerGame: 0.25,
  },
  {
    homeTeam: "St. George's Colts",
    awayTeam: 'Paget Lions',
    over15Average: 100,
    bttsAverage: 100,
    homePointsPerGame: 0.0,
    awayPointsPerGame: 3.0,
  },
  {
    homeTeam: 'Inter Sevilla',
    awayTeam: 'Coria CF',
    over15Average: 86,
    bttsAverage: 72,
    homePointsPerGame: 0.86,
    awayPointsPerGame: 1.0,
  },
  {
    homeTeam: 'Khouribga',
    awayTeam: 'Yacoub El Mansour',
    over15Average: 100,
    bttsAverage: 100,
    homePointsPerGame: 0.0,
    awayPointsPerGame: 0.0,
  },
  {
    homeTeam: 'Chicago Fire II',
    awayTeam: 'Columbus Crew II',
    over15Average: 95,
    bttsAverage: 76,
    homePointsPerGame: 1.48,
    awayPointsPerGame: 1.52,
  },
  {
    homeTeam: 'Dragón U20',
    awayTeam: 'Alianza U20',
    over15Average: 90,
    bttsAverage: 76,
    homePointsPerGame: 1.53,
    awayPointsPerGame: 1.5,
  },
  {
    homeTeam: 'Radnički Niš',
    awayTeam: 'Mladost Lučani',
    over15Average: 80,
    bttsAverage: 80,
    homePointsPerGame: 2.6,
    awayPointsPerGame: 2.6,
  },
  {
    homeTeam: 'Olympique Marseille',
    awayTeam: 'PSG',
    over15Average: 100,
    bttsAverage: 84,
    homePointsPerGame: 1.67,
    awayPointsPerGame: 2.0,
  },
  {
    homeTeam: 'Alianza Arenal',
    awayTeam: 'Social Pariacoto',
    over15Average: 100,
    bttsAverage: 84,
    homePointsPerGame: 1.33,
    awayPointsPerGame: 1.0,
  },
  {
    homeTeam: 'Honduras W',
    awayTeam: 'Guatemala W',
    over15Average: 100,
    bttsAverage: 88,
    homePointsPerGame: 1.0,
    awayPointsPerGame: 1.0,
  },
  {
    homeTeam: 'Devonshire Cougars',
    awayTeam: 'Pembroke Hamilton Club Zebras',
    over15Average: 100,
    bttsAverage: 100,
    homePointsPerGame: 0.5,
    awayPointsPerGame: 3.0,
  },
  {
    homeTeam: 'Jeunesse Evolution',
    awayTeam: 'AS Le Moule',
    over15Average: 100,
    bttsAverage: 100,
    homePointsPerGame: 1.5,
    awayPointsPerGame: 1.0,
  },
];
