export const teamsObjectList = [
  { homeTeam: 'Dynamo Le Moule', awayTeam: 'Gosier' },
  { homeTeam: 'Botafogo FR RJ', awayTeam: 'Criciuma EC SC' },
  { homeTeam: 'UDELAS', awayTeam: 'Costa del Este' },
  { homeTeam: 'Birkenhead United', awayTeam: 'Napier City Rovers' },
  { homeTeam: 'Yanbian Longding', awayTeam: 'Qingdao Red Lions' },
  { homeTeam: 'Wofoo Tai Po', awayTeam: 'Kitchee' },
  { homeTeam: 'České Budějovice U19', awayTeam: 'Opava U19' },
  { homeTeam: 'Brodarac U19', awayTeam: 'IMT Novi Beograd U19' },
  { homeTeam: 'Istra 1961 U19', awayTeam: 'Šibenik U19' },
  { homeTeam: 'Mamelodi Sundowns U23', awayTeam: 'Cape Town City U23' },
  { homeTeam: 'Cavese U19', awayTeam: 'Sorrento U19' },
  { homeTeam: 'Olympie Březová', awayTeam: 'Neratovice-Byškovice' },
  { homeTeam: 'Chomutov', awayTeam: 'Jiskra Domažlice' },
  { homeTeam: 'Trostianets', awayTeam: 'Metalist 1925 II Kharkiv' },
  { homeTeam: 'Nonthaburi FC', awayTeam: 'Thonburi University' },
  { homeTeam: 'Hamsik Academy U19', awayTeam: 'Zemplín Michalovce U19' },
  { homeTeam: 'Žilina U19', awayTeam: 'Petržalka U19' },
  { homeTeam: 'Drama Zbrosławice', awayTeam: 'Ruch Radzionków' },
  { homeTeam: 'Sparta Brodnica', awayTeam: 'Polonia Bydgoszcz' },
  { homeTeam: 'Anioły Garczegorze', awayTeam: 'Pomezania Malbork' },
  { homeTeam: 'Augsburg U19', awayTeam: 'Ulm U19' },
  { homeTeam: 'Jahn Regensburg U19', awayTeam: 'Ingolstadt U19' },
  { homeTeam: 'Chemnitzer FC U19', awayTeam: 'Dynamo Dresden U19' },
  { homeTeam: 'Mladá Boleslav U19', awayTeam: 'Pardubice U19' },
  { homeTeam: 'Baník Ostrava U19', awayTeam: 'Slovácko U19' },
  { homeTeam: 'Spartak Subotica U19', awayTeam: 'Radnički Kragujevac U19' },
  { homeTeam: 'NSA Sofia W', awayTeam: 'Etar VT' },
  { homeTeam: 'Messina U19', awayTeam: 'Casertana U19' },
  { homeTeam: 'Südburgenland / Hartberg', awayTeam: 'Rot Weiß Rankweil W' },
  { homeTeam: 'Keila', awayTeam: 'Saue' },
  { homeTeam: 'Tampines Rovers', awayTeam: 'Albirex Niigata S' },
  { homeTeam: 'Oleksandria', awayTeam: 'Vorskla' },
  { homeTeam: 'Wisła Kraków II', awayTeam: 'NKP Podhale' },
  { homeTeam: 'Huddersfield Town U18', awayTeam: 'Salford City U18' },
  { homeTeam: 'IJsselmeervogels U21', awayTeam: 'De Dijk U21' },
  { homeTeam: 'Sporting Braga U19', awayTeam: 'Oliveirense U19' },
  { homeTeam: 'Coventry City U18', awayTeam: 'Crewe Alexandra U18' },
  { homeTeam: 'Kutno', awayTeam: 'AKS SMS Łódź' },
  { homeTeam: 'Orlęta Aleksandrów Kuj.', awayTeam: 'Unia Solec Kujawski' },
  { homeTeam: 'Start Pruszcz', awayTeam: 'Tłuchowia Tłuchowo' },
  { homeTeam: 'Luzino', awayTeam: 'Pogoń Lębork' },
  { homeTeam: 'Brighton U18', awayTeam: 'Norwich City U18' },
  { homeTeam: 'West Ham United U18', awayTeam: 'Tottenham Hotspur U18' },
  { homeTeam: 'West Bromwich Albion U18', awayTeam: 'Southampton U18' },
  { homeTeam: 'Nairobi City Stars', awayTeam: 'Sofapaka' },
  { homeTeam: 'Unión Viera', awayTeam: 'San Miguel' },
  { homeTeam: 'Pécsi MFC U19', awayTeam: 'ZTE U19' },
  { homeTeam: 'Vitesse U19', awayTeam: 'AZ U19' },
  { homeTeam: 'Telstar U19', awayTeam: 'Zeeburgia U19' },
  { homeTeam: "AFC '34 U19", awayTeam: "DVS '33 U19" },
  { homeTeam: 'Morecambe U18', awayTeam: 'Preston North End U18' },
  { homeTeam: 'Notts County U18', awayTeam: 'Port Vale U18' },
  { homeTeam: 'Cheltenham Town U18', awayTeam: 'Plymouth Argyle U18' },
  { homeTeam: 'Forest Green Rovers U18', awayTeam: 'Swindon Town U18' },
  { homeTeam: 'Newport County U18', awayTeam: 'Oxford United U18' },
  { homeTeam: 'Bromley U18', awayTeam: 'Sutton United U18' },
  { homeTeam: 'Leyton Orient U18', awayTeam: 'Gillingham U18' },
  { homeTeam: 'Kayserispor', awayTeam: 'Gazişehir Gaziantep' },
  { homeTeam: 'HHC Hardenberg U21', awayTeam: 'Koninklijke HFC U21' },
  { homeTeam: 'Bristol City U18', awayTeam: 'Colchester United U18' },
  { homeTeam: 'Twente / Heracles U19', awayTeam: 'Feyenoord U19' },
  { homeTeam: 'ADO Den Haag U19', awayTeam: 'Excelsior U19' },
  { homeTeam: 'DEM U19', awayTeam: 'Hoofddorp U19' },
  { homeTeam: 'Grimsby Town U18', awayTeam: 'Walsall U18' },
  { homeTeam: 'Strømsgodset II', awayTeam: 'Lillestrøm II' },
  { homeTeam: 'Brattvåg', awayTeam: 'Viking II' },
  { homeTeam: 'Jerv', awayTeam: 'Notodden' },
  { homeTeam: 'Brann II', awayTeam: 'Lysekloster' },
  { homeTeam: 'Grorud', awayTeam: 'Vålerenga II' },
  { homeTeam: 'Eidsvold', awayTeam: 'Tromsdalen' },
  { homeTeam: 'Nakhon Ratchasima', awayTeam: 'Port FC' },
  { homeTeam: 'Thun U19', awayTeam: 'Young Boys U19' },
  { homeTeam: 'Noteć Czarnków', awayTeam: 'Wybrzeże Rewalskie Rewal' },
  { homeTeam: 'Tarup-Paarup', awayTeam: 'Middelfart II' },
  { homeTeam: 'Karlslunde', awayTeam: 'Hørsholm-Usserød' },
  { homeTeam: 'Saxan', awayTeam: 'Vulturii Cutezători' },
  { homeTeam: 'Birmingham City U18', awayTeam: 'Hull City U18' },
  { homeTeam: 'Victoria Chróścice', awayTeam: 'Polonia Głubczyce' },
  { homeTeam: 'Freiburg U19', awayTeam: 'Stuttgart U19' },
  { homeTeam: 'St. Pauli U19', awayTeam: 'Hansa Rostock U19' },
  { homeTeam: 'Kickers Offenbach U19', awayTeam: 'Karlsruher SC U19' },
  { homeTeam: 'Paderborn U19', awayTeam: 'Hannover 96 U19' },
  { homeTeam: 'Werder Bremen U19', awayTeam: 'Eintracht Braunschw. U19' },
  { homeTeam: '1860 München U19', awayTeam: 'Greuther Fürth U19' },
  { homeTeam: 'Carl Zeiss Jena U19', awayTeam: 'Hertha BSC U19' },
  { homeTeam: 'Partizan U19', awayTeam: 'Bačka Topola U19' },
  { homeTeam: 'Boeung Ket', awayTeam: 'Cambodia Tiger' },
  { homeTeam: 'Avellino U19', awayTeam: 'Ascoli U19' },
  { homeTeam: 'Chainat Hornbill', awayTeam: 'Phrae United' },
  { homeTeam: 'Leeds United U18', awayTeam: 'Derby County U18' },
  { homeTeam: 'Arsenal U18', awayTeam: 'Aston Villa U18' },
  { homeTeam: 'Leicester City U18', awayTeam: 'Fulham U18' },
  { homeTeam: 'Constructorul Leova', awayTeam: 'CS Atletic' },
  { homeTeam: 'Cvetex W', awayTeam: 'ŽFK Adrenalin' },
  { homeTeam: 'Malisheva', awayTeam: 'Prishtina' },
  { homeTeam: 'Luton Town', awayTeam: 'Watford' },
  { homeTeam: 'Marienlyst', awayTeam: 'OKS' },
  { homeTeam: 'Hedensted', awayTeam: 'Horsens II' },
  { homeTeam: 'Nakhon Si Thammarat', awayTeam: 'Chiangmai United' },
  { homeTeam: 'Chornomorets U19', awayTeam: 'Veres Rivne U19' },
  { homeTeam: 'Goa', awayTeam: 'Mumbai City' },
  { homeTeam: 'Bergdalens', awayTeam: 'Lindome' },
  { homeTeam: 'IFK Trelleborg', awayTeam: 'Simrishamn' },
  { homeTeam: 'Öster U19', awayTeam: 'Hammarby U19' },
  { homeTeam: 'Basel U19', awayTeam: 'Aarau U19' },
  { homeTeam: 'B 1909', awayTeam: 'B 1913' },
  { homeTeam: 'Oure', awayTeam: 'Esbjerg II' },
  { homeTeam: 'Krieschow', awayTeam: 'Einheit Wernigerode' },
  { homeTeam: 'Germania Halberstadt', awayTeam: 'Blau-Weiß Zorbau' },
  { homeTeam: 'Hansa Rostock', awayTeam: 'Alemannia Aachen' },
  { homeTeam: 'Ingolstadt', awayTeam: 'Verl' },
  { homeTeam: "Borussia M'gladbach II", awayTeam: 'Uerdingen' },
  { homeTeam: 'Sportfreunde Lotte', awayTeam: 'FC Bocholt' },
  { homeTeam: 'Wiener SC', awayTeam: 'LUV Graz' },
  { homeTeam: 'Emmen U21', awayTeam: 'AFC U21' },
  { homeTeam: 'Tirana', awayTeam: 'Dinamo Tirana' },
  { homeTeam: 'Werder Bremen II', awayTeam: 'Bremer SV' },
  { homeTeam: 'Dinamo Helfort', awayTeam: 'Slovan HAC' },
  { homeTeam: 'Oravské Veselé', awayTeam: 'Partizán Osrblie' },
  { homeTeam: 'Stráňavy', awayTeam: 'Sokol Medzibrod' },
  { homeTeam: 'SpVgg Landshut', awayTeam: 'ASV Burglengenfeld' },
  { homeTeam: 'Rožňava', awayTeam: 'Pavlovce nad Uhom' },
  { homeTeam: 'Tigre W', awayTeam: 'KNLE' },
  { homeTeam: 'Aumund-Vegesack', awayTeam: 'Habenhauser FV' },
  { homeTeam: 'Cardiff City U18', awayTeam: 'Charlton Athletic U18' },
  { homeTeam: 'Wehen Wiesbaden U19', awayTeam: 'Viktoria Köln U19' },
  { homeTeam: 'Cerkelladies Brugge', awayTeam: 'KdNS Heule' },
  { homeTeam: 'BEC Tero Sasana', awayTeam: 'Kanchanaburi' },
  { homeTeam: 'Fortuna Biesdorf', awayTeam: 'Stern' },
  { homeTeam: 'Vardarski', awayTeam: 'Belasica' },
  { homeTeam: 'Osogovo', awayTeam: 'Aresimi' },
  { homeTeam: 'Willem II U19', awayTeam: 'NEC U19' },
  { homeTeam: 'Albanët', awayTeam: 'Luzi United' },
  { homeTeam: 'Kota Ranger', awayTeam: 'BSRC' },
  { homeTeam: 'DPMM FC', awayTeam: 'AKSE Bersatu' },
  { homeTeam: 'Al Faisaly U19', awayTeam: 'Al Hazm U19' },
  { homeTeam: 'Holešov', awayTeam: 'Nové Sady' },
  { homeTeam: 'Preußen Reinfeld', awayTeam: 'Rotenhof' },
  { homeTeam: 'ACV', awayTeam: 'Almere City II' },
  { homeTeam: 'Smitshoek', awayTeam: 'GOES' },
  { homeTeam: 'Heerjansdam', awayTeam: 'LRC' },
  { homeTeam: 'Staphorst', awayTeam: 'AZSV' },
  { homeTeam: 'Baunatal', awayTeam: 'Fernwald' },
  { homeTeam: 'Peyia', awayTeam: 'Digenis Morphou' },
  { homeTeam: 'Anagennisi Deryneia', awayTeam: 'Akritas' },
  { homeTeam: 'Slovan Velvary', awayTeam: 'Viktoria Plzeň U19' },
  { homeTeam: 'Virtus Verona U19', awayTeam: 'Lumezzane U19' },
  { homeTeam: 'Sassuolo U19 W', awayTeam: 'Sampdoria U19 W' },
  { homeTeam: 'Praga Warszawa', awayTeam: 'LFA Szczecin W' },
  { homeTeam: 'PSV U19', awayTeam: 'Sparta Rotterdam U19' },
  { homeTeam: 'PEC Zwolle U19', awayTeam: 'Eindhoven U19' },
  { homeTeam: 'Lefkothea', awayTeam: 'Aris Limassol W' },
  { homeTeam: 'Ohod U19', awayTeam: 'Al Ahli U19' },
  { homeTeam: 'Al Ittifaq U19', awayTeam: 'Al Shabab U19' },
  { homeTeam: 'CSKA 1948 Sofia II', awayTeam: 'Dunav 2010' },
  { homeTeam: 'Debrecen', awayTeam: 'Paksi SE' },
  { homeTeam: 'Como', awayTeam: 'Parma' },
  { homeTeam: 'Lugano II', awayTeam: 'Basel II' },
  { homeTeam: 'Eckernförder SV', awayTeam: 'Lübeck II' },
  { homeTeam: 'Cittadella', awayTeam: 'Cosenza' },
  { homeTeam: 'Südtirol', awayTeam: 'Pisa' },
  { homeTeam: 'Trabzonspor', awayTeam: 'İstanbul Başakşehir' },
  { homeTeam: 'ADO Den Haag U21', awayTeam: 'De Graafschap U21' },
  { homeTeam: 'Feyenoord U21', awayTeam: 'Twente / Heracles U21' },
  { homeTeam: 'SV Auersmacher', awayTeam: 'Wormatia Worms' },
  { homeTeam: 'Eppelborn', awayTeam: 'Kaiserslautern II' },
  { homeTeam: 'Morlautern', awayTeam: 'Diefflen' },
  { homeTeam: 'ONS Sneek', awayTeam: 'WHC' },
  { homeTeam: 'Zavrč', awayTeam: 'Starše' },
  { homeTeam: 'Hajdina', awayTeam: 'Brežice' },
  { homeTeam: 'Rudar Trbovlje', awayTeam: 'Dob' },
  { homeTeam: 'Odra Wodzislaw Slaski', awayTeam: 'LKS Bełk' },
  { homeTeam: 'Przemsza Siewierz', awayTeam: 'Rozwój Katowice' },
  { homeTeam: 'Zawisza Rzgów', awayTeam: 'Warta Działoszyn' },
  { homeTeam: 'Polonia Piotrków Trybun.', awayTeam: 'Termy Poddębice' },
  { homeTeam: 'Start Brzeziny', awayTeam: 'Orzeł Nieborów' },
  { homeTeam: 'Talent Warszawa', awayTeam: 'Błonianka Błonie' },
  { homeTeam: 'Milan U20', awayTeam: 'Cremonese U20' },
  { homeTeam: 'Porawie Większyce', awayTeam: 'Piotrówka' },
  { homeTeam: 'LZS Walce', awayTeam: 'Bogacica' },
  { homeTeam: 'Śląsk Łubniany', awayTeam: 'Polonia Karłowice' },
  { homeTeam: 'Dalin Myślenice', awayTeam: 'Bochnia' },
  { homeTeam: 'Bilzen United', awayTeam: 'OH Leuven II W' },
  { homeTeam: 'Trat', awayTeam: 'Lampang' },
  { homeTeam: 'Torres U19', awayTeam: 'Pro Patria U19' },
  { homeTeam: 'Vis Pesaro U19', awayTeam: 'Lecco U19' },
  { homeTeam: 'Res Roma U19 W', awayTeam: 'Cesena U19 W' },
  { homeTeam: 'LLB Académic', awayTeam: 'Flambeau du Centre' },
  { homeTeam: 'Ngozi City', awayTeam: 'Moso Sugar' },
  { homeTeam: 'San Marino Academy', awayTeam: 'San Giovanni' },
  { homeTeam: 'Cairese', awayTeam: 'Chisola' },
  { homeTeam: 'Gozzano', awayTeam: 'Chieri' },
  { homeTeam: 'Go Ahead Eagles U19', awayTeam: 'Groningen U19' },
  { homeTeam: 'VIFK', awayTeam: 'Vaajakoski' },
  { homeTeam: 'Team Altamura U19', awayTeam: 'Pineto U19' },
  { homeTeam: 'Llanrwst United', awayTeam: 'Cerrigydrudion' },
  { homeTeam: 'Llantwit Major', awayTeam: 'Morriston Town' },
  { homeTeam: 'Clydebank', awayTeam: 'Cumnock Juniors' },
  { homeTeam: 'Volendam U21', awayTeam: 'PEC Zwolle U21' },
  { homeTeam: 'Trnje', awayTeam: 'NK Bjelovar' },
  { homeTeam: 'Tempo Praha', awayTeam: 'Mariánské Lázně' },
  { homeTeam: 'Bayer Leverkusen', awayTeam: 'Eintracht Frankfurt' },
  { homeTeam: 'Hoffenheim', awayTeam: 'Bochum' },
  { homeTeam: 'Vorwärts-Wacker 04', awayTeam: 'Buchholz' },
  { homeTeam: 'Hohenwestedt', awayTeam: 'Eutiner SV' },
  { homeTeam: 'Katwijk', awayTeam: 'Noordwijk' },
  { homeTeam: 'Vortuna Bad Leonfelden', awayTeam: 'Weißkirchen / Allhaming' },
  { homeTeam: 'Glenrothes', awayTeam: 'Sauchie Juniors' },
  { homeTeam: 'Luncarty', awayTeam: 'Whitburn Juniors' },
  { homeTeam: 'RKS Lech Rypin', awayTeam: 'Tarpan Mrocza' },
  { homeTeam: 'Bytovia Bytów', awayTeam: 'Jaguar Gdańsk' },
  { homeTeam: 'Trenčín', awayTeam: 'Skalica' },
  { homeTeam: 'Kuppenheim', awayTeam: 'Rielasingen-Arlen' },
  { homeTeam: 'Atletico Uri', awayTeam: 'Latte Dolce' },
  { homeTeam: 'Sporting Trestina', awayTeam: 'Flaminia' },
  { homeTeam: 'Molde', awayTeam: 'Sandefjord' },
  { homeTeam: 'Stocksund U19', awayTeam: 'IFK Norrköping U19' },
  { homeTeam: 'Fulham', awayTeam: 'Aston Villa' },
  { homeTeam: 'Queens Park Rangers', awayTeam: 'Portsmouth' },
  { homeTeam: 'Armagh City', awayTeam: 'Limavady United' },
  { homeTeam: 'Brühl', awayTeam: 'Grand-Saconnex' },
  { homeTeam: 'Heeslinger SC', awayTeam: 'HSC Hannover' },
  { homeTeam: 'Feirense U19', awayTeam: 'Rio Ave U19' },
  { homeTeam: 'Vitória Guimarães U19', awayTeam: 'União Nogueirense U19' },
  { homeTeam: 'Czarni Sosnowiec II', awayTeam: 'Polonia Środa Wlkp.' },
  { homeTeam: 'Hard', awayTeam: 'Rot-Weiß Rankweil' },
  { homeTeam: 'Kolping Boys', awayTeam: 'Ter Leede' },
  { homeTeam: 'Dornach', awayTeam: 'Bosna Neuchâtel' },
  { homeTeam: 'Lyss', awayTeam: 'Tavannes / Tramelan' },
  { homeTeam: 'Volos NFC', awayTeam: 'Panserraikos' },
  { homeTeam: 'Bamber Bridge', awayTeam: 'United of Manchester' },
  { homeTeam: 'Hyde United', awayTeam: 'Workington' },
  { homeTeam: 'Ilkeston Town', awayTeam: 'Guiseley' },
  { homeTeam: 'Bowers & Pitsea', awayTeam: 'Chichester City' },
  { homeTeam: 'Canvey Island', awayTeam: 'Folkestone Invicta' },
  { homeTeam: 'Dartford', awayTeam: 'Wingate & Finchley' },
  { homeTeam: 'SKRA Częstochowa', awayTeam: 'Olimpia Grudziądz' },
  { homeTeam: 'Cowdenbeath', awayTeam: "Bo'ness United" },
  { homeTeam: 'Linlithgow Rose', awayTeam: 'Tranent Juniors' },
  { homeTeam: 'Squires Gate FC', awayTeam: 'Litherland Remyca' },
  { homeTeam: 'Bugbrooke St Michaels', awayTeam: 'Sileby Rangers' },
  { homeTeam: 'Hinckley AFC', awayTeam: 'Leicester Nirvana' },
  { homeTeam: 'Lutterworth Town', awayTeam: 'Aylestone Park' },
  { homeTeam: 'Eynesbury Rovers', awayTeam: 'Coventry United' },
  { homeTeam: 'Lens II', awayTeam: 'Valenciennes II' },
  { homeTeam: 'Barton Town Old Boys', awayTeam: 'Pickering Town' },
  { homeTeam: 'Frickley Athletic', awayTeam: 'Knaresborough Town' },
  { homeTeam: 'Rossington Main', awayTeam: 'Penistone Church' },
  { homeTeam: 'Warrington Town', awayTeam: 'Oxford City' },
  { homeTeam: 'Dorking Wanderers', awayTeam: 'Salisbury' },
  { homeTeam: 'Varaždin U19', awayTeam: 'Rijeka U19' },
  { homeTeam: 'Oadby Town', awayTeam: 'St Neots Town' },
  { homeTeam: 'Chertsey Town', awayTeam: 'Plymouth Parkway' },
  { homeTeam: 'Havant & Waterlooville', awayTeam: 'Hungerford Town' },
  { homeTeam: 'Stratford Town', awayTeam: 'Lowestoft Town' },
  { homeTeam: 'Hetman Tykocin', awayTeam: 'Krypnianka Krypno' },
  { homeTeam: 'Val Miñor U19', awayTeam: 'Coruña Montañeros U19' },
  { homeTeam: 'Kingstonian', awayTeam: 'Merthyr Town' },
  { homeTeam: 'Moneyfields', awayTeam: 'Hayes & Yeading United' },
  { homeTeam: 'Southall', awayTeam: 'South Park FC' },
  { homeTeam: 'AFC Croydon Athletic', awayTeam: 'Littlehampton Town' },
  { homeTeam: 'Deal Town', awayTeam: 'Merstham' },
  { homeTeam: 'Eastbourne Town', awayTeam: 'Ashford United' },
  { homeTeam: 'Amern', awayTeam: 'Fortuna Dilkrath' },
  { homeTeam: 'Corinthian-Casuals', awayTeam: 'Abbey Rangers' },
  { homeTeam: 'Chipstead', awayTeam: 'Sheerwater' },
  { homeTeam: 'Sagrada Esperança', awayTeam: 'Académica do Lobito' },
  { homeTeam: 'Carmona', awayTeam: 'CD Lunda-Sul' },
  { homeTeam: 'Amersham Town', awayTeam: 'North Greenford United' },
  { homeTeam: 'Reading City', awayTeam: 'Risborough Rangers' },
  { homeTeam: 'AB', awayTeam: 'Suduroy' },
  { homeTeam: 'Aarau W', awayTeam: 'Zürich W' },
  { homeTeam: 'Bochum II', awayTeam: 'Lippstadt 08' },
  { homeTeam: 'AZ W', awayTeam: 'Excelsior Barendrecht W' },
  { homeTeam: 'Fortuna Sittard W', awayTeam: 'Heerenveen W' },
  { homeTeam: 'Brommapojkarna U19', awayTeam: 'IFK Göteborg U19' },
  { homeTeam: 'Grasshoppers U19', awayTeam: 'Team Ticino U19' },
  { homeTeam: 'CS Constantine', awayTeam: 'Paradou AC' },
  { homeTeam: 'Terre Sainte', awayTeam: 'Vernier' },
  { homeTeam: 'Montpellier II', awayTeam: 'Ardziv Marseille' },
  { homeTeam: 'Fos', awayTeam: 'Corte' },
  { homeTeam: 'Loyers W', awayTeam: 'Club Brugge II W' },
  { homeTeam: 'Holthausen-Biene', awayTeam: 'Grün Weiß Mühlen' },
  { homeTeam: 'Patacona', awayTeam: 'Castellón II' },
  { homeTeam: 'Haka', awayTeam: 'VPS' },
  { homeTeam: 'Phoenix Marrakech', awayTeam: 'Chabab Mohammédia W' },
  { homeTeam: 'Yacoub El Mansour', awayTeam: 'JSM Laâyoune' },
  { homeTeam: 'Rapide Oued Zem', awayTeam: 'Chabab Ben Guerir' },
  { homeTeam: 'Kriens', awayTeam: 'Vevey Sports' },
  { homeTeam: 'Ahrweiler BC', awayTeam: 'Trier-Tarforst' },
  { homeTeam: 'Viimsi', awayTeam: 'Tallinna FC Flora U21' },
  { homeTeam: 'Kolkheti Poti', awayTeam: 'Samtredia' },
  { homeTeam: 'Stade Lausanne-Ouchy', awayTeam: 'Bellinzona' },
  { homeTeam: 'De Treffers', awayTeam: 'Spakenburg' },
  { homeTeam: 'Antalyaspor', awayTeam: 'Galatasaray' },
  { homeTeam: 'Bordeaux', awayTeam: 'Avranches' },
  { homeTeam: 'Saumur', awayTeam: 'Chateaubriant Voltigeurs' },
  { homeTeam: 'Pontivy GSI', awayTeam: 'Lorient II' },
  { homeTeam: 'Olympique St Quentin', awayTeam: 'Vimy' },
  { homeTeam: 'OCPAM', awayTeam: 'Drancy JA' },
  { homeTeam: 'RC Calais', awayTeam: 'Pays de Cassel' },
  { homeTeam: 'Olympique Rovenain U19', awayTeam: 'Olympique Marseille U19' },
  { homeTeam: 'CK United U20', awayTeam: 'Bray Wanderers U20' },
  { homeTeam: 'Colegio Once México', awayTeam: 'Atlético Real Morelos' },
  { homeTeam: 'Cercle Brugge', awayTeam: 'FCV Dender EH' },
  { homeTeam: 'Istra 1961', awayTeam: 'Dinamo Zagreb' },
  { homeTeam: 'Granada CF', awayTeam: 'CD Tenerife' },
  { homeTeam: 'Bayern München', awayTeam: 'Stuttgart' },
  { homeTeam: 'La Unión', awayTeam: 'Luz Valdivia' },
  { homeTeam: 'AZ', awayTeam: 'PSV' },
  { homeTeam: 'Sparta Praha', awayTeam: 'Slovan Liberec' },
  { homeTeam: 'ROW Rybnik', awayTeam: 'Sparta Katowice' },
  { homeTeam: 'Union Mertert W', awayTeam: 'Swift Hesperingen' },
  { homeTeam: 'Al Salmiyah', awayTeam: 'Al Kuwait' },
  { homeTeam: 'AC Douane', awayTeam: 'Chemal' },
  { homeTeam: 'Sint-Truiden II', awayTeam: 'Berg en Dal' },
  { homeTeam: 'De Kempen', awayTeam: 'ASV Geel' },
  { homeTeam: 'Rus Binche', awayTeam: 'Stockay-Warfusée' },
  { homeTeam: 'Lyra-Lierse Berlaar', awayTeam: 'Cappellen' },
  { homeTeam: 'Tienen W', awayTeam: 'Ladies Genk II' },
  { homeTeam: 'Kaiserslautern', awayTeam: 'Paderborn' },
  { homeTeam: 'Celta de Vigo', awayTeam: 'Real Madrid' },
  { homeTeam: 'Go Ahead Eagles', awayTeam: 'Feyenoord' },
  { homeTeam: 'PSG', awayTeam: 'Strasbourg' },
  { homeTeam: 'CERFA', awayTeam: 'Moulien' },
  { homeTeam: 'Rayo Zuliano', awayTeam: 'Estudiantes Mérida' },
  { homeTeam: 'Grecia', awayTeam: 'Inter San Carlos' },
  { homeTeam: 'Huancavilca', awayTeam: 'Ecuagenera' },
  { homeTeam: 'Atlético JBG', awayTeam: 'Deportivo La Paz' },
  { homeTeam: 'Iztapa', awayTeam: 'Pajapita' },
  { homeTeam: 'Cacahuatique U20', awayTeam: 'Dragón U20' },
  { homeTeam: 'Caribe', awayTeam: 'Puerto Rico San Juan' },
  { homeTeam: 'DC United', awayTeam: 'Charlotte' },
  { homeTeam: 'Aguacateros CDU', awayTeam: 'Sporting Canamy' },
  { homeTeam: 'Potosinos', awayTeam: 'Magos' },
  { homeTeam: 'Luma Sports', awayTeam: 'Unión Campesinos' },
  { homeTeam: 'Diablos Tesistán', awayTeam: 'Charales Chapala' },
  { homeTeam: 'Desportivo Nacala', awayTeam: 'Black Bulls Maputo' },
  { homeTeam: 'Jaguares de Córdoba', awayTeam: 'Atlético Nacional' },
  { homeTeam: 'La Fama', awayTeam: 'Estrella' },
];
